import { NextResponse, type NextRequest } from 'next/server'
import { createSupabaseServer } from '@/lib/supabase/server'
import { createClient } from '@supabase/supabase-js'
import { decryptVaultData } from '@/lib/vault-crypto'
import { STATS_DISPLAY } from '@/data/stats'
import { resolveProviderOrder, callProvider, getProviderKey, type AIProviderId } from '@/lib/ai-provider'
import { getServiceListForPrompt, getSnapshotStats } from '@/lib/builder/executable-services'
import { executeAgent } from '@/lib/agent-studio'
import { getOrCreateCrmAccount, getActiveSession, upsertSession, incrementExecutionCount } from '@/lib/crm-provisioning'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

const ONMCP_URL = process.env.ONMCP_URL || 'http://localhost:3001'

type AISource = '0nmcp' | 'agent-studio' | 'claude-byok' | 'claude' | 'openai-byok' | 'gemini-byok' | 'openrouter-byok' | 'openrouter' | 'local' | string
type AIProvider = 'anthropic' | 'openai' | 'google' | 'openrouter'

const AI_SERVICES: AIProvider[] = ['anthropic', 'openai', 'google', 'openrouter']

// Service name aliases for knowledge base lookups
const SERVICE_ALIASES: Record<string, string> = {
  claude: 'anthropic', gpt: 'openai', chatgpt: 'openai', gemini: 'google',
  email: 'resend', sms: 'twilio', chat: 'slack', git: 'github',
  db: 'supabase', database: 'supabase', payments: 'stripe', calendar: 'google_calendar',
  sheets: 'google_sheets', drive: 'google_drive', mail: 'gmail',
}

/**
 * Query the service_knowledge table for relevant docs based on the user's message.
 */
async function getServiceKnowledge(message: string): Promise<string> {
  try {
    const admin = getAdmin()
    const lower = message.toLowerCase()

    // Extract mentioned service names
    const allServices = [
      'resend', 'stripe', 'anthropic', 'openai', 'supabase', 'sendgrid', 'slack',
      'discord', 'github', 'twilio', 'gmail', 'google_sheets', 'google_drive',
      'airtable', 'notion', 'mongodb', 'zendesk', 'jira', 'hubspot', 'mailchimp',
      'google_calendar', 'calendly', 'zoom', 'linear', 'microsoft', 'shopify',
      'smartlead', 'perplexity', 'vercel',
    ]
    const mentioned = new Set<string>()
    for (const svc of allServices) {
      if (lower.includes(svc.replace(/_/g, ' ')) || lower.includes(svc)) mentioned.add(svc)
    }
    for (const [alias, svc] of Object.entries(SERVICE_ALIASES)) {
      if (lower.includes(alias)) mentioned.add(svc)
    }

    if (mentioned.size === 0) return ''

    // Fetch relevant knowledge docs
    const { data: docs } = await admin
      .from('service_knowledge')
      .select('service_key, doc_type, title, content, section')
      .in('service_key', Array.from(mentioned))
      .eq('is_active', true)
      .order('priority', { ascending: true })
      .limit(5)

    if (!docs || docs.length === 0) return ''

    // Build knowledge context
    const parts = docs.map(d =>
      `### ${d.title} (${d.service_key} — ${d.doc_type})\n${d.content}`
    )
    return '\n\n--- SERVICE KNOWLEDGE BASE ---\nUse the following documentation to give accurate, detailed answers about these services:\n\n' + parts.join('\n\n')
  } catch {
    return ''
  }
}

/**
 * Query the council_knowledge table for relevant reasoning data
 * generated by the Brain Training Factory (offline in Claude Code).
 */
async function getCouncilKnowledge(message: string): Promise<string> {
  try {
    const admin = getAdmin()
    const lower = message.toLowerCase()

    // Detect domains mentioned in the message
    const domainKeywords: Record<string, string[]> = {
      logic: ['logic', 'reasoning', 'deduc', 'induc', 'fallac'],
      systems: ['system', 'architect', 'design', 'infrastructure', 'scale'],
      business: ['business', 'revenue', 'profit', 'strategy', 'market', 'growth'],
      ethics: ['ethic', 'moral', 'bias', 'fair', 'privacy', 'responsible'],
      workflow: ['workflow', 'automat', 'pipeline', 'process', 'orchestrat'],
      'cross-domain': ['cross-domain', 'interdisciplin', 'integrat', 'holistic'],
      optimization: ['optim', 'efficien', 'perform', 'bottleneck', 'speed'],
      'self-optimization': ['self-improv', 'meta-learn', 'self-optim', 'calibrat'],
    }

    const matchedDomains: string[] = []
    for (const [domain, keywords] of Object.entries(domainKeywords)) {
      if (keywords.some(kw => lower.includes(kw))) {
        matchedDomains.push(domain)
      }
    }

    if (matchedDomains.length === 0) return ''

    // Fetch top-scoring council knowledge for matched domains
    const { data: entries } = await admin
      .from('council_knowledge')
      .select('domain, question, synthesis, composite_score')
      .in('domain', matchedDomains)
      .gte('composite_score', 0.70)
      .order('composite_score', { ascending: false })
      .limit(3)

    if (!entries || entries.length === 0) return ''

    const parts = entries.map(e =>
      `### ${e.question} (${e.domain} — score: ${e.composite_score})\n${e.synthesis}`
    )
    return '\n\n--- COUNCIL KNOWLEDGE (Brain Training) ---\nUse the following trained reasoning to enhance your response:\n\n' + parts.join('\n\n')
  } catch {
    return ''
  }
}

/**
 * Load the user's personal knowledge base from location_knowledge_bases.
 * This makes the AI aware of their business, services, tone, FAQs, and products.
 * Each sub-location has their own KB — this is their "personal AI."
 */
async function getLocationKnowledge(userId: string): Promise<string> {
  try {
    const admin = getAdmin()

    // Find user's CRM account to get their location
    const { data: account } = await admin
      .from('user_crm_accounts')
      .select('location_id, kb_id, business_name')
      .eq('user_id', userId)
      .maybeSingle()

    if (!account?.location_id) return ''

    // Fetch their knowledge base
    const { data: kb } = await admin
      .from('location_knowledge_bases')
      .select('*')
      .eq('location_id', account.location_id)
      .maybeSingle()

    if (!kb) return ''

    // Also fetch their branding
    const { data: brand } = await admin
      .from('location_branding')
      .select('business_name, tagline, website_url, email_from_name')
      .eq('location_id', account.location_id)
      .maybeSingle()

    // Build personal context
    const parts: string[] = [
      `--- YOUR BUSINESS KNOWLEDGE BASE ---`,
      `You are ${kb.ai_name || '0n Assistant'}, the AI for ${kb.business_name || account.business_name || 'this business'}.`,
      `Tone: ${kb.tone || 'professional'}. Language: ${kb.language || 'en'}.`,
    ]

    if (kb.system_prompt) parts.push(`Behavior: ${kb.system_prompt}`)
    if (kb.business_type) parts.push(`Business type: ${kb.business_type}`)
    if (kb.industry) parts.push(`Industry: ${kb.industry}`)
    if (kb.target_audience) parts.push(`Target audience: ${kb.target_audience}`)
    if (kb.services_offered?.length) parts.push(`Services offered: ${kb.services_offered.join(', ')}`)
    if (kb.unique_selling_points?.length) parts.push(`Unique selling points: ${kb.unique_selling_points.join(', ')}`)

    // FAQs
    if (kb.faqs && Array.isArray(kb.faqs) && kb.faqs.length > 0) {
      parts.push('\nFAQs:')
      for (const faq of kb.faqs as Array<{ q: string; a: string }>) {
        parts.push(`Q: ${faq.q}\nA: ${faq.a}`)
      }
    }

    // Products/services
    if (kb.product_info && Array.isArray(kb.product_info) && kb.product_info.length > 0) {
      parts.push('\nProducts/Services: ' + JSON.stringify(kb.product_info))
    }

    // Policies
    if (kb.policies && Object.keys(kb.policies).length > 0) {
      parts.push('\nPolicies: ' + JSON.stringify(kb.policies))
    }

    // Links
    if (kb.links && Object.keys(kb.links).length > 0) {
      parts.push('\nLinks: ' + JSON.stringify(kb.links))
    }

    if (brand) {
      if (brand.website_url) parts.push(`Website: ${brand.website_url}`)
      if (brand.tagline) parts.push(`Tagline: ${brand.tagline}`)
    }

    parts.push(`\nLocation ID: ${account.location_id}`)
    parts.push(`Use this knowledge to give personalized, business-specific answers. When generating workflows, use this business context.`)
    parts.push(`--- END KNOWLEDGE BASE ---`)

    return parts.join('\n')
  } catch {
    return ''
  }
}

/**
 * Detect if user is requesting a workflow and generate + deploy it.
 * Returns the workflow definition if detected, null otherwise.
 */
async function detectAndGenerateWorkflow(
  message: string,
  userId: string,
  locationId: string | null
): Promise<{ generated: boolean; workflow?: Record<string, unknown>; reply?: string } | null> {
  const lower = message.toLowerCase()

  // Detect workflow intent
  const workflowTriggers = [
    'create a workflow', 'build a workflow', 'generate a workflow',
    'automate', 'when a contact', 'when someone', 'after every',
    'send a follow-up', 'send an email when', 'notify me when',
    'create an automation', 'set up a sequence', 'build a campaign',
    'when an appointment', 'after a booking', 'on new lead',
  ]

  const isWorkflowRequest = workflowTriggers.some(t => lower.includes(t))
  if (!isWorkflowRequest) return null

  // This is a workflow request — we'll let the AI generate it
  // and then save it to crm_agent_workflows
  return { generated: false } // Let the AI handle it with the enhanced prompt
}

// Build system prompt with REAL catalog data from snapshot
const _stats = getSnapshotStats()
const SYSTEM_PROMPT =
  `You are 0n Console, the AI assistant for the 0nMCP ecosystem — a universal AI API orchestrator with ${_stats.totalTools} tools across ${_stats.services} services.\n\n` +
  'You help users build and execute .0n workflow files (SWITCH files / RUNs).\n\n' +
  '## CRITICAL: When generating .0n workflows, you MUST ONLY use services and actions from this exact list.\n' +
  'Do NOT invent service names or action names. Every step must use a service ID and action ID from below.\n\n' +
  '## Available Services & Actions (from 0nMCP catalog)\n' +
  getServiceListForPrompt() + '\n\n' +
  '## .0n Workflow Format\n' +
  'Steps must use: { "id": "step_name", "service": "<service_id from above>", "action": "<action_id from above>", "params": {...} }\n\n' +
  '## Variable Resolution\n' +
  '- `{{system.*}}` — Auto-injected CRM auth (access_token, location_id, user_id, email)\n' +
  '- `{{launch.*}}` — Third-party API keys (defined in launch_codes block)\n' +
  '- `{{inputs.*}}` — Runtime inputs\n' +
  '- `{{step_id.output.*}}` — Chained output from previous steps\n\n' +
  '## Course Generation\n' +
  'You can generate full AI-powered courses for authenticated users.\n\n' +
  '**Marketplace endpoint** (purchase-gated): `POST /api/marketplace/courses/generate`\n' +
  'Required fields:\n' +
  '- `course_title` (string, required) — the course name\n' +
  '- `skill_level` (string) — "beginner", "intermediate", or "advanced"\n' +
  '- `module_count` (number, 2-8) — how many modules to generate\n' +
  '- `lessons_per_module` (number, 1-6) — lessons in each module\n' +
  '- `tone` (string) — "professional", "casual", "academic", etc.\n' +
  'Optional fields:\n' +
  '- `course_subtitle` (string)\n' +
  '- `target_audience` (string) — who the course is for\n' +
  '- `course_goal` (string) — learning objective\n' +
  '- `course_category` (string)\n' +
  '- `include_quizzes` (boolean, default true)\n' +
  '- `include_assignments` (boolean, default false)\n' +
  '- `keywords` (string[]) — focus topics\n' +
  '- `additional_instructions` (string) — extra guidance for the AI\n' +
  '- `locationId` (string) — CRM location ID for purchase gating\n' +
  '- `userId` (string) — the user generating the course\n\n' +
  '**Simple endpoint**: `POST /api/courses/generate`\n' +
  'Fields: `topic` (required), `audience`, `lesson_count` (3-10), `difficulty`, `style`\n\n' +
  'Both endpoints return a full course structure with modules, lessons (600-1200 words each), quizzes, and estimated duration.\n' +
  'Users must be authenticated. .0n SWITCH files can define course generation as a workflow step.\n' +
  'When users ask about creating courses, explain these options and help them fill in the fields.\n\n' +
  '## Workflow Generation & Deployment\n' +
  'When a user describes an automation outcome (e.g., "send a follow-up email 24 hours after every appointment"),\n' +
  'you MUST generate a complete workflow definition and offer to deploy it.\n\n' +
  'Workflow format for crm_agent_workflows:\n' +
  '```json\n' +
  '{\n' +
  '  "name": "Descriptive Name",\n' +
  '  "slug": "kebab-case-slug",\n' +
  '  "trigger_event": "appointment.status_changed | contact.created | contact.tag.added | schedule.daily | etc",\n' +
  '  "trigger_conditions": { "locations": ["{{location_id}}"] },\n' +
  '  "steps": [\n' +
  '    { "step": 1, "service": "crm", "action": "get_contact", "description": "Fetch contact details" },\n' +
  '    { "step": 2, "service": "crm", "action": "send_email", "description": "Send follow-up email" }\n' +
  '  ],\n' +
  '  "services": ["crm", "supabase"]\n' +
  '}\n' +
  '```\n\n' +
  'Available trigger events: appointment.status_changed, contact.created, contact.tag.added, contact.no_show,\n' +
  'conversation.message.inbound, campaign.completed, stripe.invoice.paid, schedule.daily, schedule.hourly,\n' +
  'provision.pending, kb.updated, brand.updated, command.execute\n\n' +
  'Available services for steps: crm, supabase, stripe, slack, telegram, anthropic, openai, github, vercel, figma, sanity, devto, ga4\n\n' +
  'When you generate a workflow, output it in a ```0n-workflow code block so the frontend can detect it and offer a "Deploy" button.\n' +
  'Always use the user\'s location_id from their KB context. Always explain what the workflow does in plain language first.\n\n' +
  '## Rules\n' +
  '- CRM operations use {{system.*}} — no launch codes needed\n' +
  '- Third-party services need launch_codes defined with help_url\n' +
  '- Never hardcode API keys — always use template variables\n' +
  '- Output workflows as JSON in ```0n or ```0n-workflow code blocks\n' +
  '- Be concise and technical. Use markdown.\n' +
  '- ALWAYS use the user\'s knowledge base context to personalize workflows\n' +
  '- When generating workflows, make them specific to the user\'s business type and services'

function getAdmin() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )
}

/**
 * Get a user's API key for any AI service from their Vault.
 */
async function getUserAIKey(userId: string, serviceName: string): Promise<string | null> {
  try {
    const admin = getAdmin()
    const { data: row } = await admin
      .from('user_vaults')
      .select('encrypted_key, iv, salt')
      .eq('user_id', userId)
      .eq('service_name', serviceName)
      .maybeSingle()

    if (!row?.encrypted_key || !row?.iv || !row?.salt) return null

    const plaintext = await decryptVaultData(userId, row.encrypted_key, row.iv, row.salt)
    try {
      const parsed = JSON.parse(plaintext)
      return parsed.api_key || null
    } catch {
      return plaintext || null
    }
  } catch {
    return null
  }
}

/**
 * Call Anthropic (Claude) API.
 */
async function callClaude(apiKey: string, message: string, source: AISource = 'claude-byok'): Promise<{ text: string; source: AISource } | null> {
  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 2048,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: message }],
      }),
      signal: AbortSignal.timeout(30000),
    })

    if (!res.ok) {
      const errBody = await res.text().catch(() => '')
      console.error(`[chat-byok] Claude ${res.status}: ${errBody.slice(0, 500)}`)
      return null
    }

    const data = await res.json()
    const text = data.content?.[0]?.type === 'text'
      ? data.content[0].text
      : null

    return text ? { text, source } : null
  } catch (err) {
    console.error('[chat-byok] Claude error:', err instanceof Error ? err.message : err)
    return null
  }
}

/**
 * Call Groq API (FREE — primary fallback for all users).
 * Uses system GROQ_API_KEYS pool with round-robin rotation.
 */
async function callGroq(message: string, knowledgeContext: string = ''): Promise<{ text: string; source: AISource } | null> {
  try {
    const pool = (process.env.GROQ_API_KEYS || process.env.GROQ_API_KEY || '').split(',').filter(Boolean)
    if (pool.length === 0) return null
    const key = pool[Math.floor(Math.random() * pool.length)]

    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key.trim()}` },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        max_tokens: 2048,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT + (knowledgeContext ? '\n\n' + knowledgeContext : '') },
          { role: 'user', content: message },
        ],
      }),
      signal: AbortSignal.timeout(30000),
    })

    if (!res.ok) return null
    const data = await res.json()
    const text = data.choices?.[0]?.message?.content
    return text ? { text, source: 'groq-system' as AISource } : null
  } catch {
    return null
  }
}

/**
 * Call OpenAI (GPT) API.
 */
async function callOpenAI(apiKey: string, message: string): Promise<{ text: string; source: AISource } | null> {
  try {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        max_tokens: 2048,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: message },
        ],
      }),
      signal: AbortSignal.timeout(30000),
    })

    if (!res.ok) {
      const errBody = await res.text().catch(() => '')
      console.error(`[chat-byok] OpenAI ${res.status}: ${errBody.slice(0, 500)}`)
      return null
    }

    const data = await res.json()
    const text = data.choices?.[0]?.message?.content || null

    return text ? { text, source: 'openai-byok' as AISource } : null
  } catch (err) {
    console.error('[chat-byok] OpenAI error:', err instanceof Error ? err.message : err)
    return null
  }
}

/**
 * Call Google Gemini API.
 */
async function callGemini(apiKey: string, message: string): Promise<{ text: string; source: AISource } | null> {
  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Referer': 'https://0nmcp.com' },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] },
          contents: [{ parts: [{ text: message }] }],
          generationConfig: { maxOutputTokens: 2048 },
        }),
        signal: AbortSignal.timeout(30000),
      }
    )

    if (!res.ok) {
      const errBody = await res.text().catch(() => '')
      console.error(`[chat-byok] Gemini ${res.status}: ${errBody.slice(0, 500)}`)
      return null
    }

    const data = await res.json()
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || null

    return text ? { text, source: 'gemini-byok' as AISource } : null
  } catch (err) {
    console.error('[chat-byok] Gemini error:', err instanceof Error ? err.message : err)
    return null
  }
}

/**
 * Call OpenRouter API (OpenAI-compatible gateway, 400+ models).
 */
async function callOpenRouterChat(apiKey: string, message: string): Promise<{ text: string; source: AISource } | null> {
  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://0nmcp.com',
        'X-Title': '0nMCP Console',
      },
      body: JSON.stringify({
        model: 'anthropic/claude-4-sonnet-20250522',
        max_tokens: 2048,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: message },
        ],
      }),
      signal: AbortSignal.timeout(60000),
    })

    if (!res.ok) {
      const errBody = await res.text().catch(() => '')
      console.error(`[chat-byok] OpenRouter ${res.status}: ${errBody.slice(0, 500)}`)
      return null
    }

    const data = await res.json()
    const text = data.choices?.[0]?.message?.content || null

    return text ? { text, source: 'openrouter-byok' as AISource } : null
  } catch (err) {
    console.error('[chat-byok] OpenRouter error:', err instanceof Error ? err.message : err)
    return null
  }
}

// ── Smart Local Fallback ──────────────────────────────────────
// Handles common questions without any external API call.

const LOCAL_KNOWLEDGE: Record<string, string> = {
  // Help & Getting Started
  'help': '**0n Console Commands**\n\n' +
    '`/chat` — AI assistant\n' +
    '`/vault` — Manage API keys & credentials\n' +
    '`/builder` — Visual workflow builder\n' +
    '`/flows` — Create automations\n' +
    '`/smartlead` — Cold email campaigns\n' +
    '`/social` — Social media management\n' +
    '`/store` — Marketplace templates\n' +
    '`/operations` — Active automations\n' +
    '`/terminal` — Web terminal\n' +
    '`/reporting` — Analytics & reports\n' +
    '`/convert` — Convert configs between platforms\n' +
    '`/status` — Check 0nMCP health\n\n' +
    'Type any command or describe what you want to automate.',

  'getting started': '**Getting Started with 0n Console**\n\n' +
    '1. **Connect Services** — Go to `/vault` and add API keys for the services you use\n' +
    '2. **Explore the Store** — Browse `/store` for pre-built automation templates\n' +
    '3. **Build Workflows** — Use `/builder` to visually create automations\n' +
    '4. **Run Operations** — Deploy and monitor in `/operations`\n\n' +
    `0nMCP supports **${STATS_DISPLAY.tools} tools** across **${STATS_DISPLAY.services} services**. Start by connecting your most-used services in the Vault.`,

  // Services
  'services': '**111 Connected Services**\n\n' +
    '**AI**: Anthropic (Claude), OpenAI (GPT), Google (Gemini), Perplexity\n' +
    '**CRM**: CRM (245 tools), HubSpot, Salesforce\n' +
    '**Email**: SendGrid, Gmail, Outlook, Smartlead\n' +
    '**Communication**: Slack, Discord, Twilio, WhatsApp\n' +
    '**Payments**: Stripe\n' +
    '**Development**: GitHub, Vercel, Supabase, MongoDB\n' +
    '**Productivity**: Notion, Airtable, ClickUp, Linear, Jira\n' +
    '**Marketing**: Mailchimp, Facebook Ads, Smartlead\n' +
    '**Calendar**: Google Calendar, Calendly, Zoom\n' +
    '**Other**: Google Drive, Google Sheets, Shopify, Zendesk, Zapier\n\n' +
    'Connect any service via the **Vault** (`/vault`).',

  // Smartlead
  'smartlead': '**Smartlead Integration**\n\n' +
    'Cold email outreach platform with 12 tools:\n' +
    '- **Campaigns** — Create, list, get, update campaigns\n' +
    '- **Leads** — Add, list, get leads per campaign\n' +
    '- **Sequences** — Create and list email sequences\n' +
    '- **Email Accounts** — Add and list sending accounts\n' +
    '- **Analytics** — Campaign performance stats\n\n' +
    'Go to `/smartlead` to manage campaigns, or connect your API key in `/vault` first.',

  // Vault
  'vault': '**0nVault — Encrypted Credential Storage**\n\n' +
    'Your API keys are encrypted with AES-256-GCM + PBKDF2 (100K iterations).\n\n' +
    '- Keys are encrypted client-side before storage\n' +
    '- Each service has its own encrypted entry\n' +
    '- Only YOU can decrypt your keys (derived from your user ID)\n\n' +
    'Go to `/vault` to connect services. Your keys power the Builder, Chat, and all automations.',

  // Builder
  'builder': '**Visual Workflow Builder**\n\n' +
    'Drag-and-drop workflow creation with:\n' +
    `- **Service palette** — All ${STATS_DISPLAY.services} services available as draggable nodes\n` +
    '- **Step configuration** — Set inputs, outputs, conditions per step\n' +
    '- **Connection lines** — Visual data flow between steps\n' +
    '- **Export** — Download as `.0n` SWITCH file\n' +
    '- **Import** — Load templates from the Store\n\n' +
    'Go to `/builder` to start building.',

  // Course Generator
  'course': '**AI Course Generator**\n\n' +
    'Generate full courses with AI — modules, lessons, quizzes, and assignments.\n\n' +
    '**How to use:**\n' +
    '1. Go to the Course Generator in the dashboard or store\n' +
    '2. Fill in: **course title**, **skill level** (beginner/intermediate/advanced), **module count** (2-8), **lessons per module** (1-6), **tone** (professional/casual/academic)\n' +
    '3. Optionally add: target audience, learning goal, keywords, quizzes, assignments\n' +
    '4. The AI generates 600-1200 words per lesson with real, actionable content\n\n' +
    '**API endpoints:**\n' +
    '- `POST /api/marketplace/courses/generate` — Full-featured (purchase-gated)\n' +
    '- `POST /api/courses/generate` — Simple version (topic + audience + difficulty)\n\n' +
    'You can also define course generation as a step in a .0n SWITCH file workflow.',

  // 0nMCP
  '0nmcp': '**0nMCP — Universal AI API Orchestrator**\n\n' +
    `- **${STATS_DISPLAY.tools} tools** across **${STATS_DISPLAY.services} services** in **${STATS_DISPLAY.categories} categories**\n` +
    '- **Three-Level Execution**: Pipeline > Assembly Line > Radial Burst\n' +
    '- **Patent Pending**: US Provisional #63/990,046 (Vault Container)\n' +
    '- **.0n Standard**: Universal portable config format\n' +
    '- **BYOK**: Bring your own API keys\n' +
    '- **Open Source**: Source-available, npm install `0nmcp`\n\n' +
    'Install: `npm install -g 0nmcp`\n' +
    'Run: `0nmcp serve` for HTTP mode, `0nmcp` for MCP stdio mode.',
}

function getLocalResponse(message: string): string | null {
  const lower = message.toLowerCase().trim()

  // Direct keyword matches
  for (const [key, response] of Object.entries(LOCAL_KNOWLEDGE)) {
    if (lower.includes(key)) return response
  }

  // Pattern matches
  if (lower.match(/^(hi|hello|hey|yo|sup)/)) {
    return 'Hey! I\'m the 0n Console AI. I can help you with workflow automation, service connections, and cold email campaigns.\n\nTry:\n- `/smartlead` — Manage cold email campaigns\n- `/vault` — Connect your API keys\n- `/builder` — Build visual workflows\n- `/store` — Browse automation templates\n\nOr just describe what you want to automate.'
  }

  if (lower.match(/what (can you|do you|are you)/)) {
    return LOCAL_KNOWLEDGE['help']!
  }

  if (lower.match(/how (do i|to|can i).*(connect|add|setup|configure)/)) {
    return '**Connecting a Service**\n\n1. Go to **Vault** (`/vault`)\n2. Find the service you want to connect\n3. Click it and enter your API key/credentials\n4. Your key is encrypted and stored securely\n\nOnce connected, the service is available in the Builder, Chat, and all automations.'
  }

  if (lower.match(/how (do i|to|can i).*(create|build|make).*(workflow|automation|flow)/)) {
    return '**Creating a Workflow**\n\n**Option 1 — Visual Builder** (`/builder`)\n- Drag services from the palette onto the canvas\n- Connect nodes to define data flow\n- Configure each step\'s inputs and outputs\n\n**Option 2 — AI Create** (`/flows`)\n- Describe what you want in natural language\n- AI generates the .0n SWITCH file\n\n**Option 3 — Store Templates** (`/store`)\n- Browse pre-built automations\n- Import directly to your Builder'
  }

  if (lower.match(/(cold email|outreach|campaign|lead gen)/)) {
    return LOCAL_KNOWLEDGE['smartlead']!
  }

  if (lower.match(/(price|cost|pricing|plan|upgrade|pro|team|subscription)/)) {
    return '**0n Console Plans**\n\n- **Free** — Console access, Vault, Builder, Community\n- **Pro ($19/mo)** — Priority AI, advanced workflows, premium templates\n- **Team ($49/mo)** — Multi-user, team Vault, priority support, all features\n\nAll plans include a 7-day free trial. Upgrade via the Upgrade button in the header.'
  }

  // No match — return null to signal "use AI or generic fallback"
  return null
}

export async function POST(request: NextRequest) {
  // Verify auth
  const supabase = await createSupabaseServer()
  if (!supabase) {
    return NextResponse.json({ error: 'Auth not configured' }, { status: 500 })
  }

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: {
    message?: string
    context?: {
      currentPage?: string
      brainSummary?: string
      preferences?: Record<string, unknown>
      learningTopics?: string[]
      missingServices?: string[]
      source?: 'console' | 'oncall'
    }
  }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const message = body.message?.trim()
  if (!message) {
    return NextResponse.json({ error: 'Message is required' }, { status: 400 })
  }

  // ── Build context-enhanced message for AI layers ──────────
  let enhancedMessage = message
  if (body.context) {
    const ctx = body.context
    const parts: string[] = []
    if (ctx.currentPage) parts.push(`[User is on page: ${ctx.currentPage}]`)
    if (ctx.brainSummary) parts.push(`[Context: ${ctx.brainSummary}]`)
    if (ctx.missingServices?.length) parts.push(`[Missing services: ${ctx.missingServices.join(', ')}]`)
    if (ctx.learningTopics?.length) parts.push(`[Interested in: ${ctx.learningTopics.join(', ')}]`)
    if (parts.length > 0) {
      enhancedMessage = parts.join(' ') + '\n\n' + message
    }
  }

  // ── Inject location knowledge base (personal AI per sub-account) ──
  const locationKB = await getLocationKnowledge(user.id)
  if (locationKB) {
    enhancedMessage = locationKB + '\n\n' + enhancedMessage
  }

  // ── Inject service knowledge for mentioned services ────────
  const knowledgeContext = await getServiceKnowledge(message)
  if (knowledgeContext) {
    enhancedMessage = enhancedMessage + knowledgeContext
  }

  // ── Inject council knowledge (Brain training data) ────────
  const councilContext = await getCouncilKnowledge(message)
  if (councilContext) {
    enhancedMessage = enhancedMessage + councilContext
  }

  // ── Layer 1: Try 0nMCP local server ────────────────────────
  try {
    const mcpRes = await fetch(`${ONMCP_URL}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ task: message }),
      signal: AbortSignal.timeout(5000), // Quick timeout — don't hang
    })

    if (mcpRes.ok) {
      const data = await mcpRes.json()
      console.log('[chat] Layer 1 (0nMCP) succeeded')
      return NextResponse.json({
        text: data.result || data.output || data.message || 'Task executed successfully.',
        source: '0nmcp' as const,
        status: data.status || 'completed',
        steps: data.steps_executed || data.steps || 0,
        services: data.services_used || data.services || [],
      })
    }
    console.log(`[chat] Layer 1 (0nMCP) ${mcpRes.status} — skipping`)
  } catch (err) {
    console.log('[chat] Layer 1 (0nMCP) offline:', err instanceof Error ? err.message : 'connection refused')
  }

  // ── Layer 1.5: CRM Agent Studio (Knowledge Base + MCP) ──────
  if (process.env.CRM_AGENT_STUDIO_KEY) {
    try {
      console.log('[chat] Layer 1.5 (Agent Studio) — attempting...')
      const crmAccount = await getOrCreateCrmAccount(user.id)
      const agentId = crmAccount?.default_agent_id || process.env.CRM_AGENT_STUDIO_AGENT_ID || ''
      const locationId = crmAccount?.location_id || process.env.CRM_AGENT_STUDIO_LOCATION_ID || ''

      if (agentId && locationId) {
        const existingSession = await getActiveSession(user.id, agentId).catch(() => null)

        const agentResult = await executeAgent(agentId, {
          message: enhancedMessage,
          locationId,
          executionId: existingSession || undefined,
          inputVariables: {
            userId: user.id,
            userEmail: user.email || '',
          },
        })

        if (agentResult.text && !agentResult.error) {
          if (agentResult.executionId) {
            upsertSession({ userId: user.id, executionId: agentResult.executionId, agentId, locationId }).catch(() => {})
          }
          incrementExecutionCount(user.id).catch(() => {})

          console.log('[chat] Layer 1.5 (Agent Studio) succeeded')
          return NextResponse.json({
            text: agentResult.text,
            source: 'agent-studio' as AISource,
            status: 'completed',
            executionId: agentResult.executionId,
          })
        }
        console.log('[chat] Layer 1.5 (Agent Studio) returned empty/error:', agentResult.error || 'no text')
      } else {
        console.log('[chat] Layer 1.5 skipped — no agentId or locationId')
      }
    } catch (err) {
      console.error('[chat] Layer 1.5 (Agent Studio) error:', err instanceof Error ? err.message : err)
    }
  } else {
    console.log('[chat] Layer 1.5 skipped — no CRM_AGENT_STUDIO_KEY')
  }

  // ── Layer 2: User's own AI key (BYOK — Claude, GPT, or Gemini) ──
  let byokOrder: AIProvider[] = [...AI_SERVICES]
  try {
    const admin = getAdmin()
    const { data: profile } = await admin
      .from('profiles')
      .select('core_ai_provider')
      .eq('id', user.id)
      .maybeSingle()
    const coreProvider = profile?.core_ai_provider as AIProvider | null
    if (coreProvider && AI_SERVICES.includes(coreProvider)) {
      byokOrder = [coreProvider, ...AI_SERVICES.filter(p => p !== coreProvider)]
    }
  } catch { /* continue with default order */ }

  console.log(`[chat] Layer 2 (BYOK) order: ${byokOrder.join(' → ')}`)
  for (const provider of byokOrder) {
    const userKey = await getUserAIKey(user.id, provider)
    if (!userKey) continue

    console.log(`[chat] Layer 2: trying BYOK ${provider}...`)
    let result: { text: string; source: AISource } | null = null
    if (provider === 'anthropic') {
      result = await callClaude(userKey, enhancedMessage, 'claude-byok')
    } else if (provider === 'openai') {
      result = await callOpenAI(userKey, enhancedMessage)
    } else if (provider === 'google') {
      result = await callGemini(userKey, enhancedMessage)
    } else if (provider === 'openrouter') {
      result = await callOpenRouterChat(userKey, enhancedMessage)
    }

    if (result) {
      console.log(`[chat] Layer 2: BYOK ${provider} succeeded`)
      return NextResponse.json({
        text: result.text,
        source: result.source,
      })
    }
    console.log(`[chat] Layer 2: BYOK ${provider} failed`)
  }
  console.log('[chat] Layer 2 (BYOK) — no user keys found or all failed')

  // ── Layer 3: Platform keys — all 10 providers, ordered by user preference ──
  const providerOrder = await resolveProviderOrder(user.id)

  console.log(`[chat] Layer 3 (Platform keys) order: ${providerOrder.join(' → ')}`)
  console.log(`[chat] Layer 3 keys present: ${providerOrder.map(p => `${p}=${getProviderKey(p) ? 'YES' : 'NO'}`).join(', ')}`)

  for (const provider of providerOrder) {
    const key = getProviderKey(provider)
    if (!key) continue

    console.log(`[chat] Layer 3: trying ${provider} (${key.slice(0, 8)}...)`)
    const text = await callProvider(provider, key, {
      system: SYSTEM_PROMPT,
      user: enhancedMessage,
      maxTokens: 2048,
    })
    if (text) {
      console.log(`[chat] Layer 3: ${provider} succeeded`)
      return NextResponse.json({
        text,
        source: provider as AISource,
      })
    }
    console.log(`[chat] Layer 3: ${provider} failed — next`)
  }
  console.error('[chat] Layer 3 — ALL 10 platform providers failed')

  // ── Layer 5: System Groq (FREE — always available) ──────────
  console.log('[chat] Layer 5: Trying system Groq (free)')
  const groqResult = await callGroq(enhancedMessage, knowledgeContext)
  if (groqResult) {
    return NextResponse.json(groqResult)
  }
  console.log('[chat] Layer 5: Groq failed')

  // ── Layer 6: Smart local fallback ──────────────────────────
  const localResponse = getLocalResponse(message)
  if (localResponse) {
    return NextResponse.json({
      text: localResponse,
      source: 'local' as const,
    })
  }

  // ── Layer 7: Generic helpful response ──────────────────────
  return NextResponse.json({
    text: '**I can help with that!** To unlock full AI-powered responses, connect an API key in the **Vault** — Claude, GPT-4o, or Gemini.\n\n' +
      'In the meantime, try these commands:\n' +
      '- `/vault` — Connect services\n' +
      '- `/builder` — Visual workflow builder\n' +
      '- `/store` — Browse automation templates\n' +
      '- `/help` — See all available commands',
    source: 'local' as const,
  })
}
