/**
 * EXECUTABLE SERVICES — Snapshot-driven source of truth for the builder.
 *
 * Reads from: src/data/catalog-snapshot.json
 * Generated by: scripts/sync-catalog.mjs
 *
 * To update: run `node scripts/sync-catalog.mjs` after adding services to 0nMCP,
 * then commit the new snapshot. The builder, AI prompt, and Agent Studio
 * execution all read from this same file.
 *
 * DO NOT hardcode services here — they come from the snapshot.
 */

import catalogSnapshot from '@/data/catalog-snapshot.json'

// ── Types ──

export interface CatalogAction {
  id: string
  name: string
  method: string
  path: string
  description: string
}

export interface CatalogService {
  id: string
  name: string
  category: string
  base_url: string
  auth_type: string
  actions: CatalogAction[]
  action_count: number
}

export interface CatalogMeta {
  generated_at: string
  catalog_services: number
  crm_module_tools: number
  total_tools: number
  version: string
}

// ── Snapshot data ──

export const CATALOG_META: CatalogMeta = catalogSnapshot.$meta as CatalogMeta
export const CATALOG_SERVICES: CatalogService[] = catalogSnapshot.services as CatalogService[]
export const SERVICE_IDS: string[] = catalogSnapshot.service_ids as string[]
export const SERVICE_ACTIONS: Record<string, string[]> = catalogSnapshot.service_actions as Record<string, string[]>

// ── Lookup maps (built once at import time) ──

const _serviceMap = new Map(CATALOG_SERVICES.map(s => [s.id, s]))
const _actionMap = new Map<string, Set<string>>()
for (const svc of CATALOG_SERVICES) {
  _actionMap.set(svc.id, new Set(svc.actions.map(a => a.id)))
}

// ── Public API ──

/** Check if a service ID is executable (exists in 0nMCP catalog) */
export function isExecutable(serviceId: string): boolean {
  return _serviceMap.has(serviceId)
}

/** Check if a specific service + action combo is executable */
export function isActionExecutable(serviceId: string, actionId: string): boolean {
  const actions = _actionMap.get(serviceId)
  return actions ? actions.has(actionId) : false
}

/** Get full service definition from catalog */
export function getExecutableService(serviceId: string): CatalogService | undefined {
  return _serviceMap.get(serviceId)
}

/** Get all executable service IDs */
export function getExecutableServiceIds(): string[] {
  return SERVICE_IDS
}

/** Get executable services by category */
export function getExecutableServicesByCategory(category: string): CatalogService[] {
  return CATALOG_SERVICES.filter(s => s.category === category)
}

/** Get the actions available for a service */
export function getServiceActions(serviceId: string): CatalogAction[] {
  return _serviceMap.get(serviceId)?.actions || []
}

/** Validate an entire .0n workflow — returns list of invalid steps */
export function validateWorkflowServices(
  steps: Array<{ id: string; service: string; action: string }>
): Array<{ stepId: string; service: string; action: string; error: string }> {
  const errors: Array<{ stepId: string; service: string; action: string; error: string }> = []

  for (const step of steps) {
    if (!isExecutable(step.service)) {
      errors.push({
        stepId: step.id,
        service: step.service,
        action: step.action,
        error: `Service "${step.service}" is not in the 0nMCP catalog. Add it via MCP server or use an available service.`,
      })
    } else if (!isActionExecutable(step.service, step.action)) {
      const available = SERVICE_ACTIONS[step.service]?.join(', ') || 'none'
      errors.push({
        stepId: step.id,
        service: step.service,
        action: step.action,
        error: `Action "${step.action}" not found on "${step.service}". Available: ${available}`,
      })
    }
  }

  return errors
}

// ── Coming Soon services (in builder UI but not yet in catalog) ──
// These will work once their MCP server is wired into 0nMCP.

export const COMING_SOON_SERVICES = [
  'gemini', 'perplexity', 'cohere', 'mistral', 'replicate', 'stability',
  'elevenlabs', 'deepgram', 'groq', 'salesforce', 'freshdesk',
  'planetscale', 'neon', 'turso', 'cockroachdb', 'webflow', 'mcpfed',
  'postmark', 'mailgun', 'convertkit', 'brevo', 'activecampaign', 'lemlist',
  'outlook', 'xero', 'wave', 'pinterest', 'youtube', 'twitch',
  'clickup', 'monday', 'figma', 'typeform', 'loom', 'docusign', 'trello',
  'woocommerce', 'bigcommerce', 'wordpress', 'vercel', 'netlify',
  'railway', 'render', 'aws', 'gcloud', 'telegram',
] as const

export function isComingSoon(serviceId: string): boolean {
  return (COMING_SOON_SERVICES as readonly string[]).includes(serviceId)
}

// ── AI Prompt Helpers ──

/** Generate a service list string for AI system prompts */
export function getServiceListForPrompt(): string {
  return CATALOG_SERVICES.map(svc => {
    const actions = svc.actions.map(a => a.id).join(', ')
    return `- **${svc.name}** (service: \`${svc.id}\`): ${actions}`
  }).join('\n')
}

/** Generate a compact service→actions map for AI system prompts */
export function getServiceActionsForPrompt(): string {
  return JSON.stringify(SERVICE_ACTIONS, null, 2)
}

/** Get snapshot stats for display */
export function getSnapshotStats() {
  return {
    services: CATALOG_META.catalog_services,
    catalogActions: CATALOG_META.total_tools - CATALOG_META.crm_module_tools,
    crmTools: CATALOG_META.crm_module_tools,
    totalTools: CATALOG_META.total_tools,
    generatedAt: CATALOG_META.generated_at,
  }
}
