import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: '0nCode — AI Code Snippet Designer | Generate Beautiful UI from Chat | 0nMCP',
  description: 'Design stunning code snippets and UI components from natural language. 3 design variations per prompt, real-time streaming, export production-ready HTML/CSS. Powered by AI.',
  keywords: ['0nCode', 'AI code generator', 'UI designer', 'code snippets', 'HTML generator', 'CSS generator', 'AI design'],
  openGraph: {
    title: '0nCode — AI Code Snippet Designer',
    description: 'Beautiful UI components from natural language.',
    url: 'https://0nmcp.com/products/0ncode',
  },
}

const features = [
  {
    title: '3 Variations Per Prompt',
    description: 'Every request generates 3 radically different design directions. Kinetic Wireframe, Risograph Press, Volumetric Glass — and more.',
    icon: 'grid',
  },
  {
    title: 'Real-Time Streaming',
    description: 'Watch your code write itself as the AI generates. See the component take shape line by line in real time.',
    icon: 'stream',
  },
  {
    title: 'Focus & Refine',
    description: 'Click any design to expand it full-screen, then generate variations on that specific direction until it is exactly right.',
    icon: 'focus',
  },
  {
    title: 'Code Editor',
    description: 'View, edit, and apply code changes inline. Tweak colors, spacing, or logic without leaving the tool.',
    icon: 'editor',
  },
  {
    title: 'Session History',
    description: 'Every generation is saved automatically. Navigate between past designs and pick up exactly where you left off.',
    icon: 'history',
  },
  {
    title: 'Production Ready',
    description: 'Clean HTML + CSS + JS with zero dependencies. Copy the output and ship it straight to production.',
    icon: 'ship',
  },
]

const examples = [
  {
    prompt: 'A dark mode login form with glassmorphism',
    label: 'Glassmorphic Login',
    color: '#4ade80',
  },
  {
    prompt: 'A pricing table with 3 tiers and hover animations',
    label: 'Animated Pricing',
    color: '#00d4ff',
  },
  {
    prompt: 'A testimonial carousel with star ratings',
    label: 'Testimonial Carousel',
    color: '#a78bfa',
  },
]

const pricing = [
  {
    name: 'Free',
    price: '$0',
    period: '/mo',
    description: 'Get started with AI code generation',
    features: ['5 generations per day', 'Basic HTML + CSS export', 'Session history (24h)', 'Community support'],
    cta: 'Get Started',
    href: '/console/0ncode',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$9',
    period: '/mo',
    description: 'Unlimited generations for power users',
    features: ['Unlimited generations', 'All export formats', 'Persistent session history', 'Priority AI queue', 'JS + animation export', 'Focus mode variations'],
    cta: 'Upgrade to Pro',
    href: '/console/0ncode?plan=pro',
    highlight: true,
  },
  {
    name: 'Team',
    price: '$29',
    period: '/mo',
    description: 'Collaboration for design teams',
    features: ['Everything in Pro', 'Shared design gallery', 'Team component library', 'API access', 'Priority support', 'Custom style presets'],
    cta: 'Contact Sales',
    href: '/contact?subject=0ncode-team',
    highlight: false,
  },
]

const faqs = [
  {
    q: 'What AI model does 0nCode use?',
    a: 'Gemini 3 Flash — optimized for speed and creative code generation. Each prompt returns 3 complete variations in seconds.',
  },
  {
    q: 'Can I use the generated code commercially?',
    a: 'Yes. You own all output generated by 0nCode. Use it in client projects, SaaS products, or anywhere else — no attribution required.',
  },
  {
    q: 'Does it work with React, Vue, or Svelte?',
    a: 'Generated output is vanilla HTML + CSS + JS — it works everywhere. Paste it into any framework, wrap it in a component, or use it as-is.',
  },
  {
    q: 'How is this different from Copilot?',
    a: '0nCode designs VISUAL components, not logic. Think Figma-to-code, but from words. You describe a pricing table, and you get three fully styled, production-ready designs — not a code suggestion in your editor.',
  },
]

function FeatureIcon({ icon }: { icon: string }) {
  const s = { width: 24, height: 24, stroke: '#4ade80', strokeWidth: 1.5, fill: 'none', strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const }
  switch (icon) {
    case 'grid':
      return <svg viewBox="0 0 24 24" {...s}><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></svg>
    case 'stream':
      return <svg viewBox="0 0 24 24" {...s}><path d="M4 12h4l3-9 4 18 3-9h4" /></svg>
    case 'focus':
      return <svg viewBox="0 0 24 24" {...s}><circle cx="12" cy="12" r="3" /><path d="M3 7V5a2 2 0 012-2h2M17 3h2a2 2 0 012 2v2M21 17v2a2 2 0 01-2 2h-2M7 21H5a2 2 0 01-2-2v-2" /></svg>
    case 'editor':
      return <svg viewBox="0 0 24 24" {...s}><polyline points="16 18 22 12 16 6" /><polyline points="8 6 2 12 8 18" /></svg>
    case 'history':
      return <svg viewBox="0 0 24 24" {...s}><circle cx="12" cy="12" r="9" /><polyline points="12 7 12 12 15.5 14" /></svg>
    case 'ship':
      return <svg viewBox="0 0 24 24" {...s}><path d="M5 12l5 5L20 7" /></svg>
    default:
      return null
  }
}

export default function OnCodeProductPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: '0nMCP', item: 'https://0nmcp.com' },
          { '@type': 'ListItem', position: 2, name: 'Products', item: 'https://0nmcp.com/products' },
          { '@type': 'ListItem', position: 3, name: '0nCode', item: 'https://0nmcp.com/products/0ncode' },
        ],
      },
      {
        '@type': 'Product',
        name: '0nCode',
        description: 'AI-powered code snippet designer. Generate beautiful UI components from natural language.',
        brand: { '@type': 'Organization', name: '0nMCP' },
        url: 'https://0nmcp.com/products/0ncode',
        offers: [
          { '@type': 'Offer', name: 'Free', price: '0', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
          { '@type': 'Offer', name: 'Pro', price: '9', priceCurrency: 'USD', availability: 'https://schema.org/InStock', billingIncrement: 'P1M' },
          { '@type': 'Offer', name: 'Team', price: '29', priceCurrency: 'USD', availability: 'https://schema.org/InStock', billingIncrement: 'P1M' },
        ],
      },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* ── Hero ── */}
      <section style={{
        background: 'var(--bg-deep)',
        padding: '120px 24px 100px',
        textAlign: 'center',
        position: 'relative',
        overflow: 'hidden',
      }}>
        {/* Subtle grid background */}
        <div style={{
          position: 'absolute', inset: 0, opacity: 0.04,
          backgroundImage: 'linear-gradient(rgba(74,222,128,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(74,222,128,0.3) 1px, transparent 1px)',
          backgroundSize: '48px 48px',
        }} />
        <div style={{ position: 'relative', maxWidth: 800, margin: '0 auto' }}>
          {/* Badge */}
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '6px 16px', borderRadius: 12, marginBottom: 24,
            background: 'rgba(74,222,128,0.08)', border: '1px solid rgba(74,222,128,0.2)',
          }}>
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: '#4ade80' }} />
            <span style={{ fontSize: 13, fontWeight: 600, color: '#4ade80', fontFamily: 'var(--font-mono)', letterSpacing: '0.02em' }}>AI-Powered Design Tool</span>
          </div>

          <h1 style={{
            fontSize: 'clamp(48px, 8vw, 80px)', fontWeight: 800, color: '#f0f4f8',
            fontFamily: 'var(--font-display)', margin: '0 0 16px', letterSpacing: '-0.03em', lineHeight: 1,
          }}>
            0n<span style={{ color: '#4ade80' }}>Code</span>
          </h1>
          <p style={{
            fontSize: 'clamp(20px, 3vw, 28px)', fontWeight: 600, color: '#e0e0e0',
            margin: '0 0 16px', fontFamily: 'var(--font-display)',
          }}>
            Describe it. Design it. Deploy it.
          </p>
          <p style={{
            fontSize: 16, color: '#9ca3af', maxWidth: 560, margin: '0 auto 40px',
            lineHeight: 1.7,
          }}>
            AI-powered code snippet designer. 3 unique design variations per prompt.
            Real-time streaming. Production-ready HTML/CSS.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/console/0ncode" style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              padding: '14px 32px', borderRadius: 12, border: 'none',
              background: '#4ade80', color: '#0d1117', fontWeight: 700, fontSize: 15,
              textDecoration: 'none', fontFamily: 'var(--font-display)',
            }}>
              Try 0nCode Free
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
            </Link>
            <a href="#pricing" style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              padding: '14px 32px', borderRadius: 12,
              background: 'transparent', border: '1px solid rgba(74,222,128,0.3)',
              color: '#4ade80', fontWeight: 600, fontSize: 15,
              textDecoration: 'none', fontFamily: 'var(--font-display)',
            }}>
              View Pricing
            </a>
          </div>
        </div>
      </section>

      {/* ── How It Works ── */}
      <section style={{
        background: 'var(--bg-primary)',
        padding: '100px 24px',
      }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <h2 style={{ fontSize: 36, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
              How It Works
            </h2>
            <p style={{ fontSize: 16, color: 'var(--text-muted)', maxWidth: 480, margin: '0 auto' }}>
              From idea to production-ready code in three steps.
            </p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 32 }}>
            {[
              { step: '01', title: 'Describe', desc: 'Type what you want in plain language: "a pricing table with 3 tiers and hover effects."', color: '#4ade80' },
              { step: '02', title: 'Generate', desc: 'AI creates 3 unique design variations using physical metaphors — Kinetic Wireframe, Risograph Press, Volumetric Glass.', color: '#00d4ff' },
              { step: '03', title: 'Export', desc: 'View source, edit inline, copy to clipboard, or export production-ready HTML + CSS + JS.', color: '#a78bfa' },
            ].map((s) => (
              <div key={s.step} style={{
                background: 'var(--bg-card)', border: '1px solid var(--border)',
                borderRadius: 12, padding: 32, position: 'relative',
              }}>
                <div style={{
                  fontSize: 13, fontWeight: 700, color: s.color,
                  fontFamily: 'var(--font-mono)', marginBottom: 16,
                  opacity: 0.7,
                }}>
                  STEP {s.step}
                </div>
                <h3 style={{ fontSize: 22, fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
                  {s.title}
                </h3>
                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
                  {s.desc}
                </p>
                <div style={{
                  position: 'absolute', top: 0, left: 0, right: 0, height: 2,
                  background: `linear-gradient(90deg, ${s.color}, transparent)`,
                  borderRadius: '12px 12px 0 0',
                }} />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section style={{
        background: 'var(--bg-secondary)',
        padding: '100px 24px',
      }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <h2 style={{ fontSize: 36, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
              Built for Speed and Quality
            </h2>
            <p style={{ fontSize: 16, color: 'var(--text-muted)', maxWidth: 480, margin: '0 auto' }}>
              Every feature designed to get you from prompt to production faster.
            </p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
            {features.map((f) => (
              <div key={f.title} style={{
                background: 'var(--bg-card)', border: '1px solid var(--border)',
                borderRadius: 12, padding: 28,
              }}>
                <div style={{
                  width: 44, height: 44, borderRadius: 10,
                  background: 'rgba(74,222,128,0.08)', border: '1px solid rgba(74,222,128,0.15)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  marginBottom: 16,
                }}>
                  <FeatureIcon icon={f.icon} />
                </div>
                <h3 style={{ fontSize: 17, fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 8px' }}>
                  {f.title}
                </h3>
                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
                  {f.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Examples ── */}
      <section style={{
        background: 'var(--bg-primary)',
        padding: '100px 24px',
      }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <h2 style={{ fontSize: 36, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
              See What You Can Build
            </h2>
            <p style={{ fontSize: 16, color: 'var(--text-muted)', maxWidth: 480, margin: '0 auto' }}>
              One prompt. Three designs. Infinite possibilities.
            </p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
            {examples.map((ex) => (
              <div key={ex.label} style={{
                background: 'var(--bg-card)', border: '1px solid var(--border)',
                borderRadius: 12, overflow: 'hidden',
              }}>
                {/* Mock preview area */}
                <div style={{
                  height: 180, background: 'var(--bg-deep)', position: 'relative',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  borderBottom: `1px solid var(--border)`,
                }}>
                  {/* Decorative code lines */}
                  <div style={{ padding: 20, width: '100%' }}>
                    {[0.9, 0.6, 0.75, 0.5, 0.85, 0.4].map((w, i) => (
                      <div key={i} style={{
                        height: 8, borderRadius: 4, marginBottom: 8,
                        background: `linear-gradient(90deg, ${ex.color}22, ${ex.color}08)`,
                        width: `${w * 100}%`,
                      }} />
                    ))}
                  </div>
                  <div style={{
                    position: 'absolute', bottom: 12, right: 12,
                    padding: '4px 10px', borderRadius: 6,
                    background: `${ex.color}15`, border: `1px solid ${ex.color}30`,
                    fontSize: 11, fontWeight: 600, color: ex.color,
                    fontFamily: 'var(--font-mono)',
                  }}>
                    {ex.label}
                  </div>
                </div>
                <div style={{ padding: '16px 20px' }}>
                  <div style={{
                    fontSize: 12, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)',
                    marginBottom: 4,
                  }}>
                    PROMPT
                  </div>
                  <p style={{
                    fontSize: 14, color: 'var(--text-primary)', margin: 0,
                    fontStyle: 'italic',
                  }}>
                    &quot;{ex.prompt}&quot;
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ── */}
      <section id="pricing" style={{
        background: 'var(--bg-secondary)',
        padding: '100px 24px',
      }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <h2 style={{ fontSize: 36, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
              Simple, Transparent Pricing
            </h2>
            <p style={{ fontSize: 16, color: 'var(--text-muted)', maxWidth: 480, margin: '0 auto' }}>
              Start free. Upgrade when you need more.
            </p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
            {pricing.map((plan) => (
              <div key={plan.name} style={{
                background: 'var(--bg-card)',
                border: plan.highlight ? '2px solid #4ade80' : '1px solid var(--border)',
                borderRadius: 12, padding: 32, position: 'relative',
                display: 'flex', flexDirection: 'column',
              }}>
                {plan.highlight && (
                  <div style={{
                    position: 'absolute', top: -1, left: '50%', transform: 'translateX(-50%) translateY(-50%)',
                    background: '#4ade80', color: '#0d1117', fontSize: 11, fontWeight: 700,
                    padding: '4px 14px', borderRadius: 20, fontFamily: 'var(--font-display)',
                    letterSpacing: '0.03em',
                  }}>
                    MOST POPULAR
                  </div>
                )}
                <h3 style={{ fontSize: 22, fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 4px' }}>
                  {plan.name}
                </h3>
                <p style={{ fontSize: 13, color: 'var(--text-muted)', margin: '0 0 20px' }}>
                  {plan.description}
                </p>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 4, marginBottom: 24 }}>
                  <span style={{ fontSize: 44, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', lineHeight: 1 }}>
                    {plan.price}
                  </span>
                  <span style={{ fontSize: 15, color: 'var(--text-muted)' }}>{plan.period}</span>
                </div>
                <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 28px', flex: 1 }}>
                  {plan.features.map((feat) => (
                    <li key={feat} style={{
                      display: 'flex', alignItems: 'flex-start', gap: 10,
                      fontSize: 14, color: 'var(--text-secondary)', marginBottom: 12,
                      lineHeight: 1.5,
                    }}>
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, marginTop: 2 }}><path d="M5 12l5 5L20 7" /></svg>
                      {feat}
                    </li>
                  ))}
                </ul>
                <Link href={plan.href} style={{
                  display: 'block', textAlign: 'center', padding: '12px 24px',
                  borderRadius: 12, textDecoration: 'none', fontWeight: 700, fontSize: 14,
                  fontFamily: 'var(--font-display)',
                  background: plan.highlight ? '#4ade80' : 'transparent',
                  color: plan.highlight ? '#0d1117' : '#4ade80',
                  border: plan.highlight ? 'none' : '1px solid rgba(74,222,128,0.3)',
                }}>
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section style={{
        background: 'var(--bg-primary)',
        padding: '100px 24px',
      }}>
        <div style={{ maxWidth: 720, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <h2 style={{ fontSize: 36, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 12px' }}>
              Frequently Asked Questions
            </h2>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {faqs.map((faq) => (
              <div key={faq.q} style={{
                background: 'var(--bg-card)', border: '1px solid var(--border)',
                borderRadius: 12, padding: '24px 28px',
              }}>
                <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--font-display)', margin: '0 0 10px' }}>
                  {faq.q}
                </h3>
                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
                  {faq.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Bottom CTA ── */}
      <section style={{
        background: 'var(--bg-deep)',
        padding: '100px 24px',
        textAlign: 'center',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute', inset: 0, opacity: 0.03,
          backgroundImage: 'radial-gradient(circle at 50% 50%, #4ade80 1px, transparent 1px)',
          backgroundSize: '32px 32px',
        }} />
        <div style={{ position: 'relative', maxWidth: 600, margin: '0 auto' }}>
          <h2 style={{
            fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 800, color: '#f0f4f8',
            fontFamily: 'var(--font-display)', margin: '0 0 16px', lineHeight: 1.2,
          }}>
            Your next UI component is one prompt away.
          </h2>
          <p style={{ fontSize: 16, color: '#9ca3af', margin: '0 0 36px', lineHeight: 1.7 }}>
            Stop hand-coding boilerplate. Describe what you need and let AI handle the design.
          </p>
          <Link href="/console/0ncode" style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '16px 40px', borderRadius: 12, border: 'none',
            background: '#4ade80', color: '#0d1117', fontWeight: 700, fontSize: 16,
            textDecoration: 'none', fontFamily: 'var(--font-display)',
          }}>
            Try 0nCode Free
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
          </Link>
        </div>
      </section>
    </>
  )
}
