import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: '0nCode — AI Code Snippet Designer | Generate Beautiful UI from Chat | 0nMCP',
  description: 'Design stunning code snippets and UI components from natural language. 3 design variations per prompt, real-time streaming, export production-ready HTML/CSS. Powered by AI.',
  keywords: ['0nCode', 'AI code generator', 'UI designer', 'code snippets', 'HTML generator', 'CSS generator', 'AI design'],
  openGraph: {
    title: '0nCode — AI Code Snippet Designer',
    description: 'Beautiful UI components from natural language.',
    url: 'https://0nmcp.com/products/0ncode',
  },
}

const features = [
  {
    title: '3 Variations Per Prompt',
    description: 'Every request generates 3 radically different design directions. Kinetic Wireframe, Risograph Press, Volumetric Glass — and more.',
    icon: 'grid',
  },
  {
    title: 'Real-Time Streaming',
    description: 'Watch your code write itself as the AI generates. See the component take shape line by line in real time.',
    icon: 'stream',
  },
  {
    title: 'Focus & Refine',
    description: 'Click any design to expand it full-screen, then generate variations on that specific direction until it is exactly right.',
    icon: 'focus',
  },
  {
    title: 'Code Editor',
    description: 'View, edit, and apply code changes inline. Tweak colors, spacing, or logic without leaving the tool.',
    icon: 'editor',
  },
  {
    title: 'Session History',
    description: 'Every generation is saved automatically. Navigate between past designs and pick up exactly where you left off.',
    icon: 'history',
  },
  {
    title: 'Production Ready',
    description: 'Clean HTML + CSS + JS with zero dependencies. Copy the output and ship it straight to production.',
    icon: 'ship',
  },
]

const examples = [
  {
    prompt: 'A dark mode login form with glassmorphism',
    label: 'Glassmorphic Login',
    colorClass: 'text-green-400',
    barFrom: 'from-green-400/13',
    barTo: 'to-green-400/5',
    badgeBg: 'bg-green-400/8',
    badgeBorder: 'border-green-400/19',
  },
  {
    prompt: 'A pricing table with 3 tiers and hover animations',
    label: 'Animated Pricing',
    colorClass: 'text-cyan-400',
    barFrom: 'from-cyan-400/13',
    barTo: 'to-cyan-400/5',
    badgeBg: 'bg-cyan-400/8',
    badgeBorder: 'border-cyan-400/19',
  },
  {
    prompt: 'A testimonial carousel with star ratings',
    label: 'Testimonial Carousel',
    colorClass: 'text-violet-400',
    barFrom: 'from-violet-400/13',
    barTo: 'to-violet-400/5',
    badgeBg: 'bg-violet-400/8',
    badgeBorder: 'border-violet-400/19',
  },
]

const pricing = [
  {
    name: 'Free',
    price: '$0',
    period: '/mo',
    description: 'Get started with AI code generation',
    features: ['5 generations per day', 'Basic HTML + CSS export', 'Session history (24h)', 'Community support'],
    cta: 'Get Started',
    href: '/console/0ncode',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$9',
    period: '/mo',
    description: 'Unlimited generations for power users',
    features: ['Unlimited generations', 'All export formats', 'Persistent session history', 'Priority AI queue', 'JS + animation export', 'Focus mode variations'],
    cta: 'Upgrade to Pro',
    href: '/console/0ncode?plan=pro',
    highlight: true,
  },
  {
    name: 'Team',
    price: '$29',
    period: '/mo',
    description: 'Collaboration for design teams',
    features: ['Everything in Pro', 'Shared design gallery', 'Team component library', 'API access', 'Priority support', 'Custom style presets'],
    cta: 'Contact Sales',
    href: '/contact?subject=0ncode-team',
    highlight: false,
  },
]

const faqs = [
  {
    q: 'What AI model does 0nCode use?',
    a: 'Gemini 3 Flash — optimized for speed and creative code generation. Each prompt returns 3 complete variations in seconds.',
  },
  {
    q: 'Can I use the generated code commercially?',
    a: 'Yes. You own all output generated by 0nCode. Use it in client projects, SaaS products, or anywhere else — no attribution required.',
  },
  {
    q: 'Does it work with React, Vue, or Svelte?',
    a: 'Generated output is vanilla HTML + CSS + JS — it works everywhere. Paste it into any framework, wrap it in a component, or use it as-is.',
  },
  {
    q: 'How is this different from Copilot?',
    a: '0nCode designs VISUAL components, not logic. Think Figma-to-code, but from words. You describe a pricing table, and you get three fully styled, production-ready designs — not a code suggestion in your editor.',
  },
]

function FeatureIcon({ icon }: { icon: string }) {
  const svgProps = {
    width: 24,
    height: 24,
    viewBox: '0 0 24 24',
    fill: 'none' as const,
    stroke: '#4ade80',
    strokeWidth: 1.5,
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
  }
  switch (icon) {
    case 'grid':
      return <svg {...svgProps}><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></svg>
    case 'stream':
      return <svg {...svgProps}><path d="M4 12h4l3-9 4 18 3-9h4" /></svg>
    case 'focus':
      return <svg {...svgProps}><circle cx="12" cy="12" r="3" /><path d="M3 7V5a2 2 0 012-2h2M17 3h2a2 2 0 012 2v2M21 17v2a2 2 0 01-2 2h-2M7 21H5a2 2 0 01-2-2v-2" /></svg>
    case 'editor':
      return <svg {...svgProps}><polyline points="16 18 22 12 16 6" /><polyline points="8 6 2 12 8 18" /></svg>
    case 'history':
      return <svg {...svgProps}><circle cx="12" cy="12" r="9" /><polyline points="12 7 12 12 15.5 14" /></svg>
    case 'ship':
      return <svg {...svgProps}><path d="M5 12l5 5L20 7" /></svg>
    default:
      return null
  }
}

const stepColors: Record<string, { text: string; gradientFrom: string }> = {
  '#4ade80': { text: 'text-green-400', gradientFrom: 'from-green-400' },
  '#00d4ff': { text: 'text-cyan-400', gradientFrom: 'from-cyan-400' },
  '#a78bfa': { text: 'text-violet-400', gradientFrom: 'from-violet-400' },
}

export default function OnCodeProductPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: '0nMCP', item: 'https://0nmcp.com' },
          { '@type': 'ListItem', position: 2, name: 'Products', item: 'https://0nmcp.com/products' },
          { '@type': 'ListItem', position: 3, name: '0nCode', item: 'https://0nmcp.com/products/0ncode' },
        ],
      },
      {
        '@type': 'Product',
        name: '0nCode',
        description: 'AI-powered code snippet designer. Generate beautiful UI components from natural language.',
        brand: { '@type': 'Organization', name: '0nMCP' },
        url: 'https://0nmcp.com/products/0ncode',
        offers: [
          { '@type': 'Offer', name: 'Free', price: '0', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
          { '@type': 'Offer', name: 'Pro', price: '9', priceCurrency: 'USD', availability: 'https://schema.org/InStock', billingIncrement: 'P1M' },
          { '@type': 'Offer', name: 'Team', price: '29', priceCurrency: 'USD', availability: 'https://schema.org/InStock', billingIncrement: 'P1M' },
        ],
      },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* ── Hero ── */}
      <section className="bg-[#040A1A] px-6 pt-[120px] pb-[100px] text-center relative overflow-hidden">
        {/* Subtle grid background */}
        <div className="absolute inset-0 opacity-[0.04] [background-image:linear-gradient(rgba(74,222,128,0.3)_1px,transparent_1px),linear-gradient(90deg,rgba(74,222,128,0.3)_1px,transparent_1px)] [background-size:48px_48px]" />
        <div className="relative max-w-[800px] mx-auto">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-xl mb-6 bg-green-400/[0.08] border border-green-400/20">
            <div className="w-1.5 h-1.5 rounded-full bg-green-400" />
            <span className="text-[13px] font-semibold text-green-400 font-mono tracking-[0.02em]">AI-Powered Design Tool</span>
          </div>

          <h1 className="text-[clamp(48px,8vw,80px)] font-extrabold text-[#f0f4f8] font-sans m-0 mb-4 tracking-[-0.03em] leading-none">
            0n<span className="text-green-400">Code</span>
          </h1>
          <p className="text-[clamp(20px,3vw,28px)] font-semibold text-[#e0e0e0] font-sans mb-4">
            Describe it. Design it. Deploy it.
          </p>
          <p className="text-base text-[#9ca3af] max-w-[560px] mx-auto mb-10 leading-[1.7]">
            AI-powered code snippet designer. 3 unique design variations per prompt.
            Real-time streaming. Production-ready HTML/CSS.
          </p>
          <div className="flex gap-3 justify-center flex-wrap">
            <Link href="/console/0ncode" className="inline-flex items-center gap-2 px-8 py-3.5 rounded-xl bg-green-400 text-[#0d1117] font-bold text-[15px] no-underline font-sans">
              Try 0nCode Free
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
            </Link>
            <a href="#pricing" className="inline-flex items-center gap-2 px-8 py-3.5 rounded-xl bg-transparent border border-green-400/30 text-green-400 font-semibold text-[15px] no-underline font-sans">
              View Pricing
            </a>
          </div>
        </div>
      </section>

      {/* ── How It Works ── */}
      <section className="bg-[#0d1117] px-6 py-[100px]">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-[36px] font-extrabold text-[var(--text-primary)] font-sans m-0 mb-3">
              How It Works
            </h2>
            <p className="text-base text-[var(--text-muted)] max-w-[480px] mx-auto">
              From idea to production-ready code in three steps.
            </p>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(260px,1fr))] gap-8">
            {[
              { step: '01', title: 'Describe', desc: 'Type what you want in plain language: "a pricing table with 3 tiers and hover effects."', color: '#4ade80', textClass: 'text-green-400', gradFrom: 'from-green-400' },
              { step: '02', title: 'Generate', desc: 'AI creates 3 unique design variations using physical metaphors — Kinetic Wireframe, Risograph Press, Volumetric Glass.', color: '#00d4ff', textClass: 'text-cyan-400', gradFrom: 'from-cyan-400' },
              { step: '03', title: 'Export', desc: 'View source, edit inline, copy to clipboard, or export production-ready HTML + CSS + JS.', color: '#a78bfa', textClass: 'text-violet-400', gradFrom: 'from-violet-400' },
            ].map((s) => (
              <div key={s.step} className="bg-[var(--bg-card)] border border-[var(--border)] rounded-xl p-8 relative">
                <div className={`text-[13px] font-bold ${s.textClass} font-mono mb-4 opacity-70`}>
                  STEP {s.step}
                </div>
                <h3 className="text-[22px] font-bold text-[var(--text-primary)] font-sans m-0 mb-3">
                  {s.title}
                </h3>
                <p className="text-sm text-[var(--text-secondary)] leading-[1.7] m-0">
                  {s.desc}
                </p>
                <div className={`absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r ${s.gradFrom} to-transparent rounded-t-xl`} />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section className="bg-[var(--bg-secondary)] px-6 py-[100px]">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-[36px] font-extrabold text-[var(--text-primary)] font-sans m-0 mb-3">
              Built for Speed and Quality
            </h2>
            <p className="text-base text-[var(--text-muted)] max-w-[480px] mx-auto">
              Every feature designed to get you from prompt to production faster.
            </p>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
            {features.map((f) => (
              <div key={f.title} className="bg-[var(--bg-card)] border border-[var(--border)] rounded-xl p-7">
                <div className="w-11 h-11 rounded-[10px] bg-green-400/[0.08] border border-green-400/15 flex items-center justify-center mb-4">
                  <FeatureIcon icon={f.icon} />
                </div>
                <h3 className="text-[17px] font-bold text-[var(--text-primary)] font-sans m-0 mb-2">
                  {f.title}
                </h3>
                <p className="text-sm text-[var(--text-secondary)] leading-[1.7] m-0">
                  {f.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Examples ── */}
      <section className="bg-[#0d1117] px-6 py-[100px]">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-[36px] font-extrabold text-[var(--text-primary)] font-sans m-0 mb-3">
              See What You Can Build
            </h2>
            <p className="text-base text-[var(--text-muted)] max-w-[480px] mx-auto">
              One prompt. Three designs. Infinite possibilities.
            </p>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
            {examples.map((ex) => (
              <div key={ex.label} className="bg-[var(--bg-card)] border border-[var(--border)] rounded-xl overflow-hidden">
                {/* Mock preview area */}
                <div className="h-[180px] bg-[#040A1A] relative flex items-center justify-center border-b border-[var(--border)]">
                  {/* Decorative code lines */}
                  <div className="p-5 w-full">
                    {[0.9, 0.6, 0.75, 0.5, 0.85, 0.4].map((w, i) => (
                      <div
                        key={i}
                        className={`h-2 rounded mb-2 bg-gradient-to-r ${ex.barFrom} ${ex.barTo}`}
                        style={{ width: `${w * 100}%` }}
                      />
                    ))}
                  </div>
                  <div className={`absolute bottom-3 right-3 px-2.5 py-1 rounded-md ${ex.badgeBg} border ${ex.badgeBorder} text-[11px] font-semibold ${ex.colorClass} font-mono`}>
                    {ex.label}
                  </div>
                </div>
                <div className="px-5 py-4">
                  <div className="text-xs text-[var(--text-muted)] font-mono mb-1">
                    PROMPT
                  </div>
                  <p className="text-sm text-[var(--text-primary)] m-0 italic">
                    &quot;{ex.prompt}&quot;
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ── */}
      <section id="pricing" className="bg-[var(--bg-secondary)] px-6 py-[100px]">
        <div className="max-w-[1000px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-[36px] font-extrabold text-[var(--text-primary)] font-sans m-0 mb-3">
              Simple, Transparent Pricing
            </h2>
            <p className="text-base text-[var(--text-muted)] max-w-[480px] mx-auto">
              Start free. Upgrade when you need more.
            </p>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
            {pricing.map((plan) => (
              <div
                key={plan.name}
                className={`bg-[var(--bg-card)] rounded-xl p-8 relative flex flex-col ${plan.highlight ? 'border-2 border-green-400' : 'border border-[var(--border)]'}`}
              >
                {plan.highlight && (
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-green-400 text-[#0d1117] text-[11px] font-bold px-3.5 py-1 rounded-full font-sans tracking-[0.03em]">
                    MOST POPULAR
                  </div>
                )}
                <h3 className="text-[22px] font-bold text-[var(--text-primary)] font-sans m-0 mb-1">
                  {plan.name}
                </h3>
                <p className="text-[13px] text-[var(--text-muted)] m-0 mb-5">
                  {plan.description}
                </p>
                <div className="flex items-baseline gap-1 mb-6">
                  <span className="text-[44px] font-extrabold text-[var(--text-primary)] font-sans leading-none">
                    {plan.price}
                  </span>
                  <span className="text-[15px] text-[var(--text-muted)]">{plan.period}</span>
                </div>
                <ul className="list-none p-0 m-0 mb-7 flex-1">
                  {plan.features.map((feat) => (
                    <li key={feat} className="flex items-start gap-2.5 text-sm text-[var(--text-secondary)] mb-3 leading-[1.5]">
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="shrink-0 mt-0.5"><path d="M5 12l5 5L20 7" /></svg>
                      {feat}
                    </li>
                  ))}
                </ul>
                <Link
                  href={plan.href}
                  className={`block text-center px-6 py-3 rounded-xl no-underline font-bold text-sm font-sans ${plan.highlight ? 'bg-green-400 text-[#0d1117] border-0' : 'bg-transparent text-green-400 border border-green-400/30'}`}
                >
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="bg-[#0d1117] px-6 py-[100px]">
        <div className="max-w-[720px] mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-[36px] font-extrabold text-[var(--text-primary)] font-sans m-0 mb-3">
              Frequently Asked Questions
            </h2>
          </div>
          <div className="flex flex-col gap-4">
            {faqs.map((faq) => (
              <div key={faq.q} className="bg-[var(--bg-card)] border border-[var(--border)] rounded-xl px-7 py-6">
                <h3 className="text-base font-bold text-[var(--text-primary)] font-sans m-0 mb-2.5">
                  {faq.q}
                </h3>
                <p className="text-sm text-[var(--text-secondary)] leading-[1.7] m-0">
                  {faq.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Bottom CTA ── */}
      <section className="bg-[#040A1A] px-6 py-[100px] text-center relative overflow-hidden">
        <div className="absolute inset-0 opacity-[0.03] [background-image:radial-gradient(circle_at_50%_50%,#4ade80_1px,transparent_1px)] [background-size:32px_32px]" />
        <div className="relative max-w-[600px] mx-auto">
          <h2 className="text-[clamp(28px,4vw,40px)] font-extrabold text-[#f0f4f8] font-sans m-0 mb-4 leading-[1.2]">
            Your next UI component is one prompt away.
          </h2>
          <p className="text-base text-[#9ca3af] m-0 mb-9 leading-[1.7]">
            Stop hand-coding boilerplate. Describe what you need and let AI handle the design.
          </p>
          <Link href="/console/0ncode" className="inline-flex items-center gap-2 px-10 py-4 rounded-xl bg-green-400 text-[#0d1117] font-bold text-base no-underline font-sans">
            Try 0nCode Free
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
          </Link>
        </div>
      </section>
    </>
  )
}
