-- Service Knowledge Base: API documentation + setup guides for AI-powered vault assistance
-- The AI reads this to understand how each service works, how to configure credentials,
-- troubleshoot auth issues, and guide users through setup.

CREATE TABLE IF NOT EXISTS service_knowledge (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_key TEXT NOT NULL,                    -- e.g. 'resend', 'stripe', 'anthropic'
  doc_type TEXT NOT NULL DEFAULT 'api_reference', -- api_reference, setup_guide, troubleshooting, changelog, best_practices
  title TEXT NOT NULL,
  content TEXT NOT NULL,                        -- markdown content (full doc text)
  url TEXT,                                     -- source URL for attribution
  section TEXT,                                 -- sub-section grouping (e.g. 'emails', 'domains', 'authentication')
  tags TEXT[] DEFAULT '{}',                     -- searchable tags
  priority INT DEFAULT 50,                      -- 1=critical (auth setup), 50=normal, 100=reference
  version TEXT,                                 -- API version this doc applies to
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for fast AI retrieval
CREATE INDEX IF NOT EXISTS idx_sk_service ON service_knowledge(service_key);
CREATE INDEX IF NOT EXISTS idx_sk_service_type ON service_knowledge(service_key, doc_type);
CREATE INDEX IF NOT EXISTS idx_sk_tags ON service_knowledge USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_sk_active ON service_knowledge(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_sk_priority ON service_knowledge(service_key, priority);

-- Full-text search on title + content
ALTER TABLE service_knowledge ADD COLUMN IF NOT EXISTS fts tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_sk_fts ON service_knowledge USING GIN(fts);

-- RLS: public read (AI needs access), admin write
ALTER TABLE service_knowledge ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read service knowledge" ON service_knowledge
  FOR SELECT USING (true);

CREATE POLICY "Service role can manage knowledge" ON service_knowledge
  FOR ALL USING (auth.role() = 'service_role');

-- ─── Seed: Core service documentation ───

-- Resend
INSERT INTO service_knowledge (service_key, doc_type, title, content, url, section, tags, priority) VALUES
('resend', 'setup_guide', 'Resend API Key Setup', E'# Getting Your Resend API Key\n\n1. Go to [resend.com/api-keys](https://resend.com/api-keys)\n2. Click "Create API Key"\n3. Name: "0nMCP" or your project name\n4. Permission: "Full access" (recommended for all 67 endpoints)\n5. Domain: Leave empty for unrestricted, or select a specific domain\n6. Copy the key immediately — it starts with `re_` and is only shown once\n\n## Key Format\n- Starts with `re_`\n- Example: `re_123abc456def`\n\n## Rate Limits\n- Default: 2 requests/second\n- Batch endpoint: 100 emails per request\n- Contact upgradeable rate limits available\n\n## Required Scopes\nFull access key enables all 67 endpoints:\n- Emails (send, batch, receive, attachments)\n- Domains (create, verify, manage DNS)\n- Contacts (CRUD, segments, topics)\n- Broadcasts (create, send, schedule)\n- Templates (create, publish, duplicate)\n- Webhooks (configure event notifications)\n- API Keys (manage sub-keys)', 'https://resend.com/docs/api-reference/introduction', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials'], 1),

('resend', 'api_reference', 'Resend Email Sending', E'# Send Email\n\n`POST /emails`\n\nRequired fields:\n- `from`: Sender email (must be from verified domain)\n- `to`: Recipient(s) — string or array\n- `subject`: Email subject line\n\nOptional fields:\n- `html`: HTML body\n- `text`: Plain text body\n- `reply_to`: Reply-to address\n- `cc`, `bcc`: Carbon copy recipients\n- `attachments`: Array of { filename, content (base64) }\n- `tags`: Array of { name, value } for analytics\n- `scheduled_at`: ISO datetime for delayed sending\n- `headers`: Custom email headers\n\n## Batch Sending\n`POST /emails/batch` — send up to 100 emails in one request.\nBody is an array of email objects.\n\n## Cancel Scheduled\n`POST /emails/{id}/cancel` — cancel before delivery.\n\n## Common Errors\n- 422: Invalid `from` address (domain not verified)\n- 429: Rate limit exceeded (2 req/sec default)\n- 403: API key lacks permission', 'https://resend.com/docs/api-reference/emails/send-email', 'emails', ARRAY['send', 'email', 'batch', 'transactional'], 10),

('resend', 'api_reference', 'Resend Domain Management', E'# Domain Management\n\n## Add Domain\n`POST /domains` — body: `{ "name": "example.com" }`\n\nOptional: region (us-east-1, eu-west-1, sa-east-1), open_tracking, click_tracking\n\n## Verify Domain\n`POST /domains/{id}/verify` — triggers async DNS verification.\n\nRequired DNS records (returned on create):\n- SPF: TXT record\n- DKIM: 3x CNAME records\n- DMARC: TXT record (recommended)\n- MX: For receiving emails\n\n## Domain States\n- `not_started` → `pending` → `verified` → `active`\n- `failed` — DNS records not found\n\n## Troubleshooting\n- DNS propagation takes 24-72 hours\n- CNAME records must NOT be proxied (Cloudflare: grey cloud)\n- SPF must include `include:amazonses.com`', 'https://resend.com/docs/api-reference/domains/create-domain', 'domains', ARRAY['domain', 'dns', 'verify', 'spf', 'dkim'], 10),

('resend', 'api_reference', 'Resend Contacts & Segments', E'# Contact Management\n\n## Create Contact\n`POST /contacts` — body: `{ "email": "user@example.com" }`\nOptional: first_name, last_name, unsubscribed, segments, properties\n\n## Segments\nSegments group contacts for targeted broadcasts.\n- `POST /segments` — create segment\n- `POST /contacts/{id}/segments/{segment_id}` — add contact to segment\n- `DELETE /contacts/{id}/segments/{segment_id}` — remove from segment\n\n## Contact Properties\nCustom fields for contacts (like CRM custom fields).\n- `POST /contact-properties` — body: `{ "name": "company", "type": "string" }`\n- Types: string, number, boolean, date\n\n## Topics\nManage email subscription preferences.\n- `PATCH /contacts/{id}/topics` — update opt-in/opt-out per topic', 'https://resend.com/docs/api-reference/contacts/create-contact', 'contacts', ARRAY['contacts', 'segments', 'topics', 'properties', 'lists'], 10),

('resend', 'api_reference', 'Resend Broadcasts', E'# Broadcast Emails\n\nBroadcasts send to an entire segment (like a newsletter).\n\n## Create\n`POST /broadcasts` — body:\n```json\n{\n  "segment_id": "seg_xxx",\n  "from": "newsletter@yourdomain.com",\n  "subject": "Monthly Update",\n  "html": "<h1>Hello!</h1>"\n}\n```\n\n## Send\n`POST /broadcasts/{id}/send` — optional `scheduled_at` for delayed delivery.\n\n## Lifecycle\n1. Create (draft status)\n2. Update content/segment as needed\n3. Send immediately or schedule\n4. Track delivery via webhooks\n\n## Delete\nOnly draft broadcasts can be deleted. Scheduled broadcasts are cancelled.', 'https://resend.com/docs/api-reference/broadcasts/create-broadcast', 'broadcasts', ARRAY['broadcast', 'newsletter', 'bulk', 'segment'], 10),

('resend', 'api_reference', 'Resend Templates & Webhooks', E'# Email Templates\n\n## Create Template\n`POST /templates` — body: `{ "name": "Welcome", "html": "<h1>Welcome!</h1>" }`\n\nTemplates can use React Email components when rendered server-side.\n\n## Publish\n`POST /templates/{id}/publish` — makes template available for use.\n\n## Duplicate\n`POST /templates/{id}/duplicate` — creates a copy for A/B testing.\n\n# Webhooks\n\n## Events\n- `email.sent` — email accepted by Resend\n- `email.delivered` — delivered to recipient\n- `email.delivery_delayed` — temporary delivery issue\n- `email.complained` — recipient marked as spam\n- `email.bounced` — hard bounce\n- `email.opened` — email opened (requires tracking)\n- `email.clicked` — link clicked (requires tracking)\n\n## Create Webhook\n`POST /webhooks` — body:\n```json\n{\n  "endpoint_url": "https://yourapp.com/webhooks/resend",\n  "events": ["email.delivered", "email.bounced"]\n}\n```\n\nAll webhook payloads include: type, created_at, data (email details).', 'https://resend.com/docs/api-reference/templates/create-template', 'templates', ARRAY['template', 'webhook', 'events', 'react-email'], 10),

('resend', 'troubleshooting', 'Resend Common Issues', E'# Troubleshooting Resend\n\n## "Domain not verified" (422)\n- Check DNS records are correctly configured\n- Wait 24-72 hours for propagation\n- Disable Cloudflare proxy on CNAME records\n- Run `POST /domains/{id}/verify` to retry\n\n## "Rate limit exceeded" (429)\n- Default: 2 requests/second\n- Use batch endpoint for bulk sends (100/request)\n- Implement exponential backoff\n- Contact Resend for higher limits\n\n## "API key invalid" (401)\n- Keys start with `re_`\n- Keys are shown once on creation — regenerate if lost\n- Check key hasn''t been deleted or rotated\n\n## Emails going to spam\n- Verify domain with SPF, DKIM, and DMARC\n- Use a consistent `from` address\n- Avoid spam trigger words in subject\n- Warm up new domains gradually\n\n## Webhooks not firing\n- Verify endpoint URL is publicly accessible (HTTPS)\n- Check webhook events are correct\n- Verify endpoint returns 200 status\n- Use `GET /webhooks` to check status', 'https://resend.com/docs/introduction', 'troubleshooting', ARRAY['troubleshooting', 'errors', 'debug', 'spam'], 5),

-- Stripe
('stripe', 'setup_guide', 'Stripe API Key Setup', E'# Getting Your Stripe API Key\n\n1. Go to [dashboard.stripe.com/apikeys](https://dashboard.stripe.com/apikeys)\n2. Copy "Secret key" (starts with `sk_live_` or `sk_test_`)\n3. For restricted keys: API Keys > Create restricted key\n\n## Key Types\n- `sk_test_*` — test mode (no real charges)\n- `sk_live_*` — live mode (real payments)\n- `rk_live_*` — restricted live key (limited permissions)\n- `rk_test_*` — restricted test key\n\n## Webhook Secret\nFor webhook verification:\n1. Developers > Webhooks > Add endpoint\n2. URL: `https://yourapp.com/api/webhooks/stripe`\n3. Select events to listen for\n4. Copy "Signing secret" (starts with `whsec_`)\n\n## Common Permissions for Restricted Keys\n- Charges: Read/Write\n- Customers: Read/Write\n- Products: Read/Write\n- Prices: Read/Write\n- Subscriptions: Read/Write\n- Invoices: Read/Write\n- Payment Intents: Read/Write', 'https://stripe.com/docs/keys', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'webhook'], 1),

('stripe', 'troubleshooting', 'Stripe Common Issues', E'# Troubleshooting Stripe\n\n## "Invalid API key" (401)\n- Ensure using correct mode (test vs live)\n- Check key hasn''t been rolled/revoked\n- sk_test_ keys only work with test data\n\n## Webhook signature verification failed\n- Ensure using correct webhook secret (whsec_)\n- Raw request body must be used (not parsed JSON)\n- Clock skew tolerance: 300 seconds\n\n## "No such customer" (404)\n- Customer IDs are mode-specific (test vs live)\n- Verify customer exists: `GET /v1/customers/{id}`\n\n## Payment declined\n- Test cards: 4242424242424242 (success), 4000000000000002 (decline)\n- Check SCA/3DS requirements for EU cards', 'https://stripe.com/docs', 'troubleshooting', ARRAY['troubleshooting', 'errors', 'debug'], 5),

-- Anthropic
('anthropic', 'setup_guide', 'Anthropic API Key Setup', E'# Getting Your Anthropic API Key\n\n1. Go to [console.anthropic.com/settings/keys](https://console.anthropic.com/settings/keys)\n2. Click "Create Key"\n3. Name it (e.g., "0nMCP")\n4. Copy the key — starts with `sk-ant-api03-`\n\n## Models Available\n- `claude-opus-4-6` — Most capable, best for complex reasoning\n- `claude-sonnet-4-6` — Balanced performance and speed\n- `claude-haiku-4-5-20251001` — Fastest, lowest cost\n\n## Rate Limits\n- Tier 1: 60 RPM, 60K tokens/min\n- Tier 2: 1000 RPM, 80K tokens/min\n- Tier 3: 2000 RPM, 160K tokens/min\n- Tier 4: 4000 RPM, 400K tokens/min\n\n## Pricing (per 1M tokens)\n- Opus: $15 input / $75 output\n- Sonnet: $3 input / $15 output\n- Haiku: $0.25 input / $1.25 output', 'https://docs.anthropic.com/en/api/getting-started', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'claude'], 1),

-- Supabase
('supabase', 'setup_guide', 'Supabase Credentials Setup', E'# Getting Your Supabase Credentials\n\n## Project URL\n1. Go to [supabase.com/dashboard](https://supabase.com/dashboard)\n2. Select your project\n3. Settings > API\n4. Copy "Project URL" — format: `https://{ref}.supabase.co`\n\n## Anon Key (Public)\n- Settings > API > "anon public" key\n- Safe to use in client-side code\n- Limited by Row Level Security policies\n- Starts with `eyJhbGci...`\n\n## Service Role Key (Secret)\n- Settings > API > "service_role" key\n- NEVER expose client-side\n- Bypasses all RLS policies\n- Full admin access to all tables\n\n## Database Connection\n- Settings > Database > Connection string\n- Direct: `postgresql://postgres:{password}@db.{ref}.supabase.co:5432/postgres`\n- Pooler: `postgresql://postgres.{ref}:{password}@aws-0-{region}.pooler.supabase.com:6543/postgres`', 'https://supabase.com/docs/guides/api', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'database'], 1),

-- SendGrid
('sendgrid', 'setup_guide', 'SendGrid API Key Setup', E'# Getting Your SendGrid API Key\n\n1. Go to [app.sendgrid.com/settings/api_keys](https://app.sendgrid.com/settings/api_keys)\n2. Click "Create API Key"\n3. Name: "0nMCP"\n4. Permissions: "Full Access" or "Restricted Access"\n5. Copy the key — starts with `SG.`\n\n## Key Format\n- Starts with `SG.`\n- Example: `SG.xxxxxx.yyyyyy`\n\n## Sender Verification\nBefore sending, verify sender identity:\n- Settings > Sender Authentication\n- Domain Authentication (recommended)\n- OR Single Sender Verification (quick start)', 'https://docs.sendgrid.com/ui/account-and-settings/api-keys', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials'], 1),

-- Slack
('slack', 'setup_guide', 'Slack Bot Token Setup', E'# Getting Your Slack Bot Token\n\n1. Go to [api.slack.com/apps](https://api.slack.com/apps)\n2. Create New App > From Scratch\n3. OAuth & Permissions > Bot Token Scopes:\n   - `chat:write` — send messages\n   - `channels:read` — list channels\n   - `users:read` — list users\n   - `channels:manage` — create channels\n4. Install App to Workspace\n5. Copy "Bot User OAuth Token" — starts with `xoxb-`\n\n## Token Types\n- `xoxb-` — Bot token (recommended)\n- `xoxp-` — User token (acts as user)\n- `xoxe-` — Enterprise token\n\n## Webhook URL (alternative)\nFor simple notifications without a bot:\n1. Incoming Webhooks > Activate\n2. Add New Webhook to Workspace\n3. Select channel\n4. Copy URL', 'https://api.slack.com/authentication/token-types', 'authentication', ARRAY['bot_token', 'setup', 'auth', 'credentials'], 1),

-- Discord
('discord', 'setup_guide', 'Discord Bot Token Setup', E'# Getting Your Discord Bot Token\n\n1. Go to [discord.com/developers/applications](https://discord.com/developers/applications)\n2. New Application > Name it\n3. Bot section > Reset Token\n4. Copy the token\n5. Enable required Intents:\n   - Message Content Intent (for reading messages)\n   - Server Members Intent (for member info)\n\n## Inviting Your Bot\n1. OAuth2 > URL Generator\n2. Scopes: `bot`, `applications.commands`\n3. Bot Permissions: Send Messages, Read Message History, etc.\n4. Copy generated URL > Open in browser > Select server\n\n## Token Format\n- Long string (no prefix)\n- Keep SECRET — anyone with token controls the bot', 'https://discord.com/developers/docs/getting-started', 'authentication', ARRAY['bot_token', 'setup', 'auth', 'credentials'], 1),

-- GitHub
('github', 'setup_guide', 'GitHub Personal Access Token Setup', E'# Getting Your GitHub Token\n\n## Fine-grained Token (Recommended)\n1. Settings > Developer Settings > Personal Access Tokens > Fine-grained tokens\n2. Generate new token\n3. Select repositories (specific or all)\n4. Permissions:\n   - Contents: Read/Write (repos, commits)\n   - Issues: Read/Write\n   - Pull Requests: Read/Write\n   - Actions: Read/Write (workflows)\n\n## Classic Token\n1. Settings > Developer Settings > Personal Access Tokens > Tokens (classic)\n2. Scopes: `repo`, `workflow`, `admin:org` as needed\n3. Starts with `ghp_`\n\n## Token Formats\n- `ghp_` — Classic personal access token\n- `github_pat_` — Fine-grained personal access token\n- `ghs_` — GitHub App installation token', 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'token'], 1),

-- Twilio
('twilio', 'setup_guide', 'Twilio Credentials Setup', E'# Getting Your Twilio Credentials\n\n1. Go to [console.twilio.com](https://console.twilio.com)\n2. Dashboard shows:\n   - Account SID: starts with `AC`\n   - Auth Token: click to reveal\n\n## Phone Number\nBuy a number: Phone Numbers > Manage > Buy a Number\n\n## Credential Format\n- Account SID: `ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` (34 chars)\n- Auth Token: 32-character hex string\n\n## API Sub-accounts\nFor isolation between projects:\n- Accounts > Subaccounts > Create\n- Each gets own SID + Auth Token', 'https://www.twilio.com/docs/usage/api', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'sms'], 1),

-- OpenAI
('openai', 'setup_guide', 'OpenAI API Key Setup', E'# Getting Your OpenAI API Key\n\n1. Go to [platform.openai.com/api-keys](https://platform.openai.com/api-keys)\n2. Create new secret key\n3. Name it and set permissions\n4. Copy — starts with `sk-`\n\n## Models\n- `gpt-4o` — Most capable multimodal\n- `gpt-4o-mini` — Fast and cheap\n- `o1` / `o3` — Reasoning models\n- `dall-e-3` — Image generation\n- `whisper-1` — Audio transcription\n- `tts-1` / `tts-1-hd` — Text-to-speech\n\n## Organization ID\nSettings > Organization > Copy ID (starts with `org-`)\n\n## Rate Limits\nVary by tier (usage-based):\n- Tier 1: 500 RPM, 30K TPM\n- Tier 5: 10K RPM, 10M TPM', 'https://platform.openai.com/docs/api-reference', 'authentication', ARRAY['api_key', 'setup', 'auth', 'credentials', 'ai'], 1),

-- Gmail
('gmail', 'setup_guide', 'Gmail OAuth Setup', E'# Gmail API Setup\n\nGmail requires OAuth 2.0 (not API keys).\n\n1. [console.cloud.google.com](https://console.cloud.google.com)\n2. APIs & Services > Enable Gmail API\n3. Credentials > Create OAuth Client ID\n4. Application type: Web application\n5. Add authorized redirect URIs\n\n## Scopes\n- `gmail.send` — Send emails\n- `gmail.readonly` — Read emails\n- `gmail.modify` — Read/write/send\n- `gmail.labels` — Manage labels\n\n## Service Account (server-to-server)\nFor automated access without user consent:\n1. Create service account\n2. Enable domain-wide delegation\n3. Share Gmail access with service account email', 'https://developers.google.com/gmail/api/quickstart', 'authentication', ARRAY['oauth', 'setup', 'auth', 'credentials', 'google'], 1);
