/**
 * OnPress Plugin Generator
 * Generates a WordPress plugin from a DesignSystem.
 * Ported from class-onpress-plugin-generator.php.
 */

import type { DesignSystem, GenerationConfig, ExtractedComponent } from './types'

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'default'
}

function pascalCase(str: string): string {
  return str.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')
}

function guessHtmlTag(node: ExtractedComponent): string {
  const size = node.styles?.fontSize ?? 16
  if (size >= 32) return 'h1'
  if (size >= 24) return 'h2'
  if (size >= 20) return 'h3'
  if (size >= 18) return 'h4'
  return 'p'
}

function inlineStyle(styles: ExtractedComponent['styles']): string {
  const css: string[] = []
  if (styles.color) css.push(`color:${styles.color}`)
  if (styles.fontSize) css.push(`font-size:${styles.fontSize}px`)
  if (styles.fontFamily) css.push(`font-family:'${styles.fontFamily}'`)
  if (styles.fontWeight) css.push(`font-weight:${styles.fontWeight}`)
  return css.join('; ')
}

function generateBlockRender(comp: ExtractedComponent): string {
  const cls = slugify(comp.name)
  let inner = ''

  for (const child of comp.children ?? []) {
    if (child.type === 'TEXT' && child.text) {
      const tag = guessHtmlTag(child)
      const style = inlineStyle(child.styles)
      inner += `<${tag} style="${style}">${escapePhp(child.text)}</${tag}>\n    `
    } else if (child.children?.length) {
      const style = inlineStyle(child.styles)
      inner += `<div class="${slugify(child.name)}" style="${style}">\n`
      for (const grandchild of child.children) {
        if (grandchild.type === 'TEXT' && grandchild.text) {
          const tag = guessHtmlTag(grandchild)
          inner += `        <${tag}>${escapePhp(grandchild.text)}</${tag}>\n`
        }
      }
      inner += `    </div>\n    `
    }
  }

  return `<?php defined('ABSPATH') || exit; ?>\n<div class="${cls}">\n    ${inner}</div>`
}

function escapePhp(str: string): string {
  return str.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/**
 * Generate a WordPress plugin file map from a DesignSystem.
 */
export function generatePlugin(
  ds: DesignSystem,
  config: GenerationConfig
): Record<string, string> {
  const { slug, name } = config
  const prefix = slug.replace(/-/g, '_')
  const className = pascalCase(slug)
  const files: Record<string, string> = {}
  const colors = ds.colors
  const components = ds.components.slice(0, 15)

  // ── Block registrations ──
  const blockRegistrations = components.map(comp => {
    const blockSlug = slugify(comp.name)
    return `
        register_block_type('${slug}/${blockSlug}', [
            'style' => '${slug}-styles',
            'render_callback' => function($atts) {
                $file = ${prefix.toUpperCase()}_PATH . 'blocks/${blockSlug}/render.php';
                if (file_exists($file)) { ob_start(); include $file; return ob_get_clean(); }
                return '<div class="${blockSlug}"><!-- ${comp.name} --></div>';
            },
        ]);`
  }).join('\n')

  const shortcodeRegistrations = components.map(comp => {
    const scName = slugify(comp.name).replace(/-/g, '_')
    return `        add_shortcode('${scName}', [$this, 'sc_${scName}']);`
  }).join('\n')

  const shortcodeMethods = components.map(comp => {
    const scName = slugify(comp.name).replace(/-/g, '_')
    const blockSlug = slugify(comp.name)
    return `
    public function sc_${scName}($atts) {
        $atts = shortcode_atts(['class' => ''], $atts);
        $file = ${prefix.toUpperCase()}_PATH . 'blocks/${blockSlug}/render.php';
        if (file_exists($file)) { ob_start(); include $file; return ob_get_clean(); }
        return '<div class="${blockSlug} ' . esc_attr($atts['class']) . '"><!-- ${comp.name} --></div>';
    }`
  }).join('\n')

  const settingsFields = colors.slice(0, 10).map(c => {
    const cs = slugify(c.name)
    return `        register_setting('${prefix}_options', '${prefix}_color_${cs}', ['default' => '${c.value.hex}']);`
  }).join('\n')

  // ── Main plugin file ──
  files[`${slug}.php`] = `<?php
/**
 * Plugin Name: ${name}
 * Plugin URI: https://0nmcp.com/onpress
 * Description: Custom WordPress plugin generated from Figma design by OnPress. Includes custom Gutenberg blocks, shortcodes, admin settings, and design tokens.
 * Version: 1.0.0
 * Author: Generated by OnPress
 * Author URI: https://0nmcp.com
 * License: GPL v2 or later
 * Text Domain: ${slug}
 * Requires at least: 6.0
 * Requires PHP: 7.4
 */

defined('ABSPATH') || exit;

define('${prefix.toUpperCase()}_VERSION', '1.0.0');
define('${prefix.toUpperCase()}_PATH', plugin_dir_path(__FILE__));
define('${prefix.toUpperCase()}_URL', plugin_dir_url(__FILE__));

class ${className} {

    public function __construct() {
        add_action('init', [$this, 'register_blocks']);
        add_action('init', [$this, 'register_shortcodes']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_styles']);
        add_action('admin_menu', [$this, 'add_settings_page']);
        add_action('admin_init', [$this, 'register_settings']);
        add_action('rest_api_init', [$this, 'register_rest_routes']);
    }

    public function enqueue_styles() {
        wp_enqueue_style('${slug}-styles', ${prefix.toUpperCase()}_URL . 'assets/style.css', [], ${prefix.toUpperCase()}_VERSION);
    }

    public function register_blocks() {${blockRegistrations}
    }

    public function register_shortcodes() {
${shortcodeRegistrations}
    }
${shortcodeMethods}

    public function add_settings_page() {
        add_options_page('${name}', '${name}', 'manage_options', '${slug}-settings', [$this, 'render_settings']);
    }

    public function register_settings() {
${settingsFields}
    }

    public function render_settings() {
        include ${prefix.toUpperCase()}_PATH . 'admin/settings.php';
    }

    public function register_rest_routes() {
        register_rest_route('${slug}/v1', '/tokens', [
            'methods' => 'GET',
            'callback' => function() {
                return ['colors' => get_option('${prefix}_design_tokens', []), 'version' => ${prefix.toUpperCase()}_VERSION];
            },
            'permission_callback' => function() { return current_user_can('manage_options'); },
        ]);
    }
}

new ${className}();
`

  // ── Plugin CSS ──
  const cssVars = colors.map(c =>
    `  --${slugify(c.name)}: ${c.value.hex};`
  ).join('\n')

  const componentCss = components.map(comp => {
    const cls = slugify(comp.name)
    const rules: string[] = []
    if (comp.styles.fills[0]?.color) rules.push(`background: ${comp.styles.fills[0].color}`)
    const cr = comp.styles.cornerRadius
    if (typeof cr === 'number' && cr > 0) rules.push(`border-radius: ${cr}px`)
    if (comp.layout) {
      const dir = comp.layout.mode === 'VERTICAL' ? 'column' : 'row'
      rules.push(`display: flex`)
      rules.push(`flex-direction: ${dir}`)
      rules.push(`gap: ${comp.layout.itemSpacing}px`)
      rules.push(`padding: ${comp.layout.paddingTop}px ${comp.layout.paddingRight}px ${comp.layout.paddingBottom}px ${comp.layout.paddingLeft}px`)
    }
    return `.${cls} {\n  ${rules.join(';\n  ')};\n}`
  }).join('\n\n')

  files['assets/style.css'] = `/* ${name} — Design tokens from Figma */
:root {
${cssVars}
}

${componentCss}
`

  // ── Admin settings page ──
  const colorFields = colors.slice(0, 10).map(c => {
    const cs = slugify(c.name)
    return `            <tr>
                <th><label for="${prefix}_color_${cs}">${c.name}</label></th>
                <td>
                    <input type="color" id="${prefix}_color_${cs}" name="${prefix}_color_${cs}"
                           value="<?php echo esc_attr(get_option('${prefix}_color_${cs}', '${c.value.hex}')); ?>" />
                    <code><?php echo esc_html(get_option('${prefix}_color_${cs}', '${c.value.hex}')); ?></code>
                </td>
            </tr>`
  }).join('\n')

  files['admin/settings.php'] = `<div class="wrap">
    <h1>${name} — Design Tokens</h1>
    <p>Colors extracted from your Figma design. Customize them below.</p>
    <form method="post" action="options.php">
        <?php settings_fields('${prefix}_options'); ?>
        <table class="form-table">
${colorFields}
        </table>
        <?php submit_button(); ?>
    </form>
</div>
`

  // ── Block render templates ──
  for (const comp of components) {
    const blockSlug = slugify(comp.name)
    files[`blocks/${blockSlug}/render.php`] = generateBlockRender(comp)
  }

  return files
}
