/**
 * OnPress Theme Generator
 * Generates a complete WordPress theme from a DesignSystem.
 * Ported from class-onpress-theme-generator.php + ui.html generateTheme().
 */

import type { DesignSystem, GenerationConfig } from './types'

// ── Helpers ──

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'default'
}

function fontWeightToNumber(style: string): number {
  const map: Record<string, number> = {
    'Thin': 100, 'ExtraLight': 200, 'Light': 300, 'Regular': 400,
    'Medium': 500, 'SemiBold': 600, 'Semi Bold': 600, 'Bold': 700,
    'ExtraBold': 800, 'Extra Bold': 800, 'Black': 900,
  }
  if (!isNaN(Number(style))) return Number(style)
  return map[style] || 400
}

function guessTypographySelector(name: string): string {
  const lower = name.toLowerCase()
  if (lower.includes('h1') || lower.includes('heading 1') || lower.includes('display')) return 'h1, .wp-block-heading:where(h1)'
  if (lower.includes('h2') || lower.includes('heading 2')) return 'h2, .wp-block-heading:where(h2)'
  if (lower.includes('h3') || lower.includes('heading 3')) return 'h3, .wp-block-heading:where(h3)'
  if (lower.includes('h4') || lower.includes('heading 4')) return 'h4, .wp-block-heading:where(h4)'
  if (lower.includes('h5') || lower.includes('heading 5')) return 'h5'
  if (lower.includes('h6') || lower.includes('heading 6')) return 'h6'
  if (lower.includes('body') || lower.includes('paragraph')) return 'p, .wp-block-paragraph'
  if (lower.includes('caption') || lower.includes('small')) return 'small, figcaption, .wp-block-image figcaption'
  if (lower.includes('button') || lower.includes('cta')) return '.btn, .wp-block-button__link'
  if (lower.includes('link')) return 'a'
  return `.text-${slugify(name)}`
}

/**
 * Generate a complete WordPress theme file map from a DesignSystem.
 */
export function generateTheme(
  ds: DesignSystem,
  config: GenerationConfig
): Record<string, string> {
  const { slug, name } = config
  const prefix = slug.replace(/-/g, '_')
  const files: Record<string, string> = {}

  // Collect unique font families
  const fontFamilies = [...new Set(ds.typography.map(t => t.value.fontFamily).filter(Boolean))]

  // ── style.css ──
  const cssVars = ds.colors.map(c =>
    `  --${slugify(c.name)}: ${c.value.hex};`
  ).join('\n')

  const typographyRules = ds.typography.map(t => {
    const selector = guessTypographySelector(t.name)
    const weight = fontWeightToNumber(String(t.value.fontWeight))
    const rules = [
      t.value.fontFamily ? `font-family: '${t.value.fontFamily}', sans-serif` : '',
      `font-weight: ${weight}`,
      t.value.fontSize ? `font-size: ${t.value.fontSize}px` : '',
      t.value.lineHeight ? `line-height: ${t.value.lineHeight}px` : '',
      t.value.letterSpacing ? `letter-spacing: ${t.value.letterSpacing}px` : '',
    ].filter(Boolean).join(';\n  ')
    return `${selector} {\n  ${rules};\n}`
  }).join('\n\n')

  const effectRules = ds.effects.map(e => {
    if (Array.isArray(e.value)) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const shadow = e.value.find((v: any) => v.type === 'DROP_SHADOW')
      if (shadow) {
        return `.shadow-${slugify(e.name)} { box-shadow: ${shadow.offset?.x || 0}px ${shadow.offset?.y || 4}px ${shadow.radius}px ${shadow.spread || 0}px ${shadow.color || 'rgba(0,0,0,0.1)'}; }`
      }
    }
    return ''
  }).filter(Boolean).join('\n')

  const primaryColor = ds.colors[0]?.value?.hex || '#333333'
  const firstRadius = ds.radii[0]?.value || 8

  files['style.css'] = `/*
Theme Name: ${name}
Theme URI: https://0nmcp.com/onpress
Author: Generated by OnPress
Author URI: https://0nmcp.com
Description: Custom WordPress theme generated from Figma design by OnPress. Every color, font, spacing token, and component maps directly to your design file.
Version: 1.0.0
Requires at least: 6.0
Requires PHP: 7.4
Text Domain: ${slug}
License: GPL v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Tags: custom-colors, custom-logo, editor-style, block-styles, wide-blocks, full-site-editing
*/

/* ── Design Tokens from Figma ── */
:root {
${cssVars}
${ds.spacing.map(s => `  --spacing-${s.value}: ${s.value}px;`).join('\n')}
${ds.radii.map(r => `  --radius-${r.value}: ${r.value}px;`).join('\n')}
}

/* ── Reset & Base ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; }
body {
  font-family: ${fontFamilies[0] ? `'${fontFamilies[0]}', ` : ''}system-ui, -apple-system, sans-serif;
  color: #1a1a1a;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--${slugify(ds.colors[0]?.name || 'primary')}); text-decoration: none; }
a:hover { opacity: 0.8; }
img { max-width: 100%; height: auto; display: block; }
.container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }

/* ── Typography ── */
${typographyRules}

/* ── Navigation ── */
.primary-menu { list-style: none; display: flex; gap: 24px; margin: 0; padding: 0; }
.primary-menu li a { color: #333; font-weight: 500; font-size: 15px; transition: color 0.2s; }
.primary-menu li a:hover { color: ${primaryColor}; }

/* ── Buttons ── */
.wp-block-button__link, .btn {
  display: inline-block;
  padding: 12px 28px;
  background: ${primaryColor};
  color: #fff;
  border: none;
  border-radius: var(--radius-${firstRadius});
  font-family: var(--font-primary, inherit);
  font-weight: 600;
  font-size: 14px;
  cursor: pointer;
  transition: all 0.2s;
}
.wp-block-button__link:hover, .btn:hover { opacity: 0.9; transform: translateY(-1px); }

/* ── Effects ── */
${effectRules}

/* ── Responsive ── */
@media (max-width: 768px) {
  body { font-size: 15px; }
  .container { padding: 0 16px; }
  h1, .wp-block-heading:where(h1) { font-size: 28px !important; }
  h2, .wp-block-heading:where(h2) { font-size: 22px !important; }
}
`

  // ── functions.php ──
  const colorPalette = ds.colors.map(c =>
    `        [\n            'name'  => '${c.name}',\n            'slug'  => '${slugify(c.name)}',\n            'color' => '${c.value.hex}',\n        ],`
  ).join('\n')

  const customizerSettings = ds.colors.slice(0, 10).map(c => {
    const cs = slugify(c.name)
    return `
    $wp_customize->add_setting('${slug}_color_${cs}', ['default' => '${c.value.hex}', 'sanitize_callback' => 'sanitize_hex_color']);
    $wp_customize->add_control(new WP_Customize_Color_Control($wp_customize, '${slug}_color_${cs}', [
        'label'   => __('${c.name}', '${slug}'),
        'section' => '${slug}_colors',
    ]));`
  }).join('\n')

  const customizerCSS = ds.colors.slice(0, 10).map(c =>
    `    $css .= '--${slugify(c.name)}:' . get_theme_mod('${slug}_color_${slugify(c.name)}', '${c.value.hex}') . ';';`
  ).join('\n')

  const blockPatterns = ds.components.slice(0, 20).map(comp =>
    `
    register_block_pattern('${slug}/${slugify(comp.name)}', [
        'title'       => __('${comp.name}', '${slug}'),
        'description' => __('Generated from Figma component: ${comp.name}', '${slug}'),
        'categories'  => ['${slug}'],
        'content'     => '',
    ]);`
  ).join('\n')

  const googleFontsUrl = fontFamilies.length > 0
    ? `\n    wp_enqueue_style('${slug}-fonts',
        'https://fonts.googleapis.com/css2?${fontFamilies.map(f => `family=${f.replace(/ /g, '+')}:wght@300;400;500;600;700;800;900`).join('&')}&display=swap',
        [], null
    );`
    : ''

  files['functions.php'] = `<?php
/**
 * ${name} — Generated by OnPress (Figma to WordPress)
 * https://0nmcp.com/onpress
 *
 * @package ${slug}
 */

defined('ABSPATH') || exit;

define('${prefix.toUpperCase()}_VERSION', '1.0.0');

function ${prefix}_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script']);
    add_theme_support('custom-logo', ['height' => 100, 'width' => 350, 'flex-height' => true, 'flex-width' => true]);
    add_theme_support('wp-block-styles');
    add_theme_support('align-wide');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_editor_style('style.css');

    add_theme_support('editor-color-palette', [
${colorPalette}
    ]);

    register_nav_menus([
        'primary' => __('Primary Menu', '${slug}'),
        'footer'  => __('Footer Menu', '${slug}'),
    ]);
}
add_action('after_setup_theme', '${prefix}_setup');

function ${prefix}_scripts() {
    wp_enqueue_style('${slug}-style', get_stylesheet_uri(), [], ${prefix.toUpperCase()}_VERSION);${googleFontsUrl}
}
add_action('wp_enqueue_scripts', '${prefix}_scripts');

function ${prefix}_block_patterns() {
    register_block_pattern_category('${slug}', ['label' => __('${name}', '${slug}')]);
${blockPatterns}
}
add_action('init', '${prefix}_block_patterns');

function ${prefix}_customizer($wp_customize) {
    $wp_customize->add_section('${slug}_colors', ['title' => __('Theme Colors', '${slug}'), 'priority' => 30]);
${customizerSettings}
}
add_action('customize_register', '${prefix}_customizer');

function ${prefix}_customizer_css() {
    $css = '<style>:root{';
${customizerCSS}
    $css .= '}</style>';
    echo $css;
}
add_action('wp_head', '${prefix}_customizer_css');

function ${prefix}_widgets() {
    register_sidebar(['name' => __('Sidebar', '${slug}'), 'id' => 'sidebar-1', 'before_widget' => '<div class="widget %2$s">', 'after_widget' => '</div>', 'before_title' => '<h3 class="widget-title">', 'after_title' => '</h3>']);
    register_sidebar(['name' => __('Footer', '${slug}'), 'id' => 'footer-1', 'before_widget' => '<div class="footer-widget %2$s">', 'after_widget' => '</div>', 'before_title' => '<h4 class="footer-widget-title">', 'after_title' => '</h4>']);
}
add_action('widgets_init', '${prefix}_widgets');
`

  // ── Template files ──
  const primarySlug = slugify(ds.colors[0]?.name || 'primary')

  files['header.php'] = `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<header id="masthead" class="site-header">
    <div class="container" style="display:flex; justify-content:space-between; align-items:center; padding:20px;">
        <div class="site-branding">
            <?php if (has_custom_logo()) : the_custom_logo(); else : ?>
                <a href="<?php echo esc_url(home_url('/')); ?>" style="font-size:24px; font-weight:800; color:var(--${primarySlug});">
                    <?php bloginfo('name'); ?>
                </a>
            <?php endif; ?>
        </div>
        <nav id="site-navigation" class="main-navigation">
            <?php wp_nav_menu(['theme_location' => 'primary', 'menu_class' => 'primary-menu', 'container' => false]); ?>
        </nav>
    </div>
</header>
`

  files['footer.php'] = `<footer id="colophon" class="site-footer" style="background:#111; color:#999; padding:40px 0; margin-top:60px;">
    <div class="container">
        <div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(200px, 1fr)); gap:30px;">
            <?php if (is_active_sidebar('footer-1')) : dynamic_sidebar('footer-1'); endif; ?>
        </div>
        <div style="text-align:center; margin-top:30px; padding-top:20px; border-top:1px solid #222; font-size:13px;">
            &copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.
        </div>
    </div>
</footer>

<?php wp_footer(); ?>
</body>
</html>
`

  files['index.php'] = `<?php get_header(); ?>

<main id="primary" class="site-main container">
    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
            <?php if (has_post_thumbnail()) : ?>
                <div class="post-thumbnail"><?php the_post_thumbnail('large'); ?></div>
            <?php endif; ?>
            <h2 class="entry-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div class="entry-excerpt"><?php the_excerpt(); ?></div>
        </article>
    <?php endwhile; the_posts_navigation(); else : ?>
        <p><?php esc_html_e('No posts found.', '${slug}'); ?></p>
    <?php endif; ?>
</main>

<?php get_sidebar(); get_footer(); ?>
`

  files['single.php'] = `<?php get_header(); ?>

<main class="container" style="max-width:800px; margin:40px auto;">
    <?php while (have_posts()) : the_post(); ?>
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
            <?php if (has_post_thumbnail()) : ?>
                <div class="post-thumbnail" style="margin-bottom:24px; border-radius:var(--radius-${firstRadius}); overflow:hidden;">
                    <?php the_post_thumbnail('large'); ?>
                </div>
            <?php endif; ?>
            <h1 class="entry-title"><?php the_title(); ?></h1>
            <div class="entry-meta" style="color:#888; font-size:14px; margin:12px 0 24px;">
                <?php echo get_the_date(); ?> &bull; <?php the_author(); ?>
            </div>
            <div class="entry-content"><?php the_content(); ?></div>
        </article>
        <?php comments_template(); ?>
    <?php endwhile; ?>
</main>

<?php get_footer(); ?>
`

  files['page.php'] = `<?php get_header(); ?>

<main class="container" style="padding:40px 20px;">
    <?php while (have_posts()) : the_post(); ?>
        <article <?php post_class(); ?>>
            <h1 class="entry-title"><?php the_title(); ?></h1>
            <div class="entry-content"><?php the_content(); ?></div>
        </article>
    <?php endwhile; ?>
</main>

<?php get_footer(); ?>
`

  files['sidebar.php'] = `<?php if (is_active_sidebar('sidebar-1')) : ?>
<aside id="secondary" class="widget-area">
    <?php dynamic_sidebar('sidebar-1'); ?>
</aside>
<?php endif; ?>
`

  files['404.php'] = `<?php get_header(); ?>

<main class="container" style="text-align:center; padding:80px 20px;">
    <h1 style="font-size:72px; font-weight:900; opacity:0.2;">404</h1>
    <h2>Page Not Found</h2>
    <p style="color:#888; margin:16px 0 32px;">The page you're looking for doesn't exist.</p>
    <a href="<?php echo home_url('/'); ?>" class="btn">Go Home</a>
</main>

<?php get_footer(); ?>
`

  files['search.php'] = `<?php get_header(); ?>

<main class="container" style="padding:40px 20px;">
    <h1>Search Results for: <?php the_search_query(); ?></h1>
    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
        <article <?php post_class(); ?> style="margin:24px 0; padding-bottom:24px; border-bottom:1px solid #eee;">
            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div><?php the_excerpt(); ?></div>
        </article>
    <?php endwhile; the_posts_navigation(); else : ?>
        <p>No results found.</p>
    <?php endif; ?>
</main>

<?php get_footer(); ?>
`

  files['archive.php'] = `<?php get_header(); ?>

<main class="container" style="padding:40px 20px;">
    <h1><?php the_archive_title(); ?></h1>
    <?php the_archive_description('<div style="color:#888; margin-bottom:24px;">', '</div>'); ?>
    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
        <article <?php post_class(); ?> style="margin-bottom:32px;">
            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div style="color:#888; font-size:13px;"><?php echo get_the_date(); ?></div>
            <div><?php the_excerpt(); ?></div>
        </article>
    <?php endwhile; the_posts_navigation(); else : ?>
        <p>No posts found.</p>
    <?php endif; ?>
</main>

<?php get_footer(); ?>
`

  files['comments.php'] = `<?php if (post_password_required()) return; ?>
<div id="comments" class="comments-area" style="margin-top:40px; padding-top:40px; border-top:1px solid #eee;">
    <?php if (have_comments()) : ?>
        <h3><?php comments_number('No Comments', '1 Comment', '% Comments'); ?></h3>
        <ol class="comment-list" style="list-style:none; padding:0;">
            <?php wp_list_comments(['style' => 'ol', 'short_ping' => true]); ?>
        </ol>
    <?php endif; ?>
    <?php comment_form(); ?>
</div>
`

  files['screenshot.txt'] = 'Replace this file with a 1200x900 screenshot.png of your theme.'

  // WooCommerce support if enabled
  if (config.options?.woocommerce) {
    files['woocommerce.php'] = '<?php get_header(); woocommerce_content(); get_footer(); ?>'
    files['woocommerce/archive-product.php'] = '<?php defined("ABSPATH") || exit; get_header("shop"); woocommerce_content(); get_footer("shop"); ?>'
  }

  return files
}
